CREATE FUNCTION [dbo].[DecodeCyrillicJSON]
(
    @pString NVARCHAR(MAX)
)
RETURNS @returntable TABLE
(
    String NVARCHAR(MAX)
)
AS
BEGIN

    INSERT @returntable
    SELECT @pString

    UPDATE @returntable SET String = REPLACE(String,'\u0430',N'а') 
    UPDATE @returntable SET String = REPLACE(String,'\u0431',N'б')
    UPDATE @returntable SET String = REPLACE(String,'\u0432',N'в')
    UPDATE @returntable SET String = REPLACE(String,'\u0433',N'г')
    UPDATE @returntable SET String = REPLACE(String,'\u0434',N'д')
    UPDATE @returntable SET String = REPLACE(String,'\u0435',N'е')
    UPDATE @returntable SET String = REPLACE(String,'\u0451',N'ё')
    UPDATE @returntable SET String = REPLACE(String,'\u0436',N'ж')
    UPDATE @returntable SET String = REPLACE(String,'\u0437',N'з')
    UPDATE @returntable SET String = REPLACE(String,'\u0438',N'и')
    UPDATE @returntable SET String = REPLACE(String,'\u0439',N'й')
    UPDATE @returntable SET String = REPLACE(String,'\u043a',N'к')
    UPDATE @returntable SET String = REPLACE(String,'\u043b',N'л')
    UPDATE @returntable SET String = REPLACE(String,'\u043c',N'м')
    UPDATE @returntable SET String = REPLACE(String,'\u043d',N'н')
    UPDATE @returntable SET String = REPLACE(String,'\u043e',N'о')
    UPDATE @returntable SET String = REPLACE(String,'\u043f',N'п')
    UPDATE @returntable SET String = REPLACE(String,'\u0440',N'р')
    UPDATE @returntable SET String = REPLACE(String,'\u0441',N'с')
    UPDATE @returntable SET String = REPLACE(String,'\u0442',N'т')
    UPDATE @returntable SET String = REPLACE(String,'\u0443',N'у')
    UPDATE @returntable SET String = REPLACE(String,'\u0444',N'ф')
    UPDATE @returntable SET String = REPLACE(String,'\u0445',N'х')
    UPDATE @returntable SET String = REPLACE(String,'\u0446',N'ц')
    UPDATE @returntable SET String = REPLACE(String,'\u0447',N'ч')
    UPDATE @returntable SET String = REPLACE(String,'\u0448',N'ш')
    UPDATE @returntable SET String = REPLACE(String,'\u0449',N'щ')
    UPDATE @returntable SET String = REPLACE(String,'\u044a',N'ъ')
    UPDATE @returntable SET String = REPLACE(String,'\u044b',N'ы')
    UPDATE @returntable SET String = REPLACE(String,'\u044c',N'ь')
    UPDATE @returntable SET String = REPLACE(String,'\u044d',N'э')
    UPDATE @returntable SET String = REPLACE(String,'\u044e',N'ю')
    UPDATE @returntable SET String = REPLACE(String,'\u044f',N'я')
    UPDATE @returntable SET String = REPLACE(String,'\u0410',N'А')
    UPDATE @returntable SET String = REPLACE(String,'\u0411',N'Б')
    UPDATE @returntable SET String = REPLACE(String,'\u0412',N'В')
    UPDATE @returntable SET String = REPLACE(String,'\u0413',N'Г')
    UPDATE @returntable SET String = REPLACE(String,'\u0414',N'Д')
    UPDATE @returntable SET String = REPLACE(String,'\u0415',N'Е')
    UPDATE @returntable SET String = REPLACE(String,'\u0401',N'Ё')
    UPDATE @returntable SET String = REPLACE(String,'\u0416',N'Ж')
    UPDATE @returntable SET String = REPLACE(String,'\u0417',N'З')
    UPDATE @returntable SET String = REPLACE(String,'\u0418',N'И')
    UPDATE @returntable SET String = REPLACE(String,'\u0419',N'Й')
    UPDATE @returntable SET String = REPLACE(String,'\u041a',N'К')
    UPDATE @returntable SET String = REPLACE(String,'\u041b',N'Л')
    UPDATE @returntable SET String = REPLACE(String,'\u041c',N'М')
    UPDATE @returntable SET String = REPLACE(String,'\u041d',N'Н')
    UPDATE @returntable SET String = REPLACE(String,'\u041e',N'О')
    UPDATE @returntable SET String = REPLACE(String,'\u041f',N'П')
    UPDATE @returntable SET String = REPLACE(String,'\u0420',N'Р')
    UPDATE @returntable SET String = REPLACE(String,'\u0421',N'С')
    UPDATE @returntable SET String = REPLACE(String,'\u0422',N'Т')
    UPDATE @returntable SET String = REPLACE(String,'\u0423',N'У')
    UPDATE @returntable SET String = REPLACE(String,'\u0424',N'Ф')
    UPDATE @returntable SET String = REPLACE(String,'\u0425',N'Х')
    UPDATE @returntable SET String = REPLACE(String,'\u0426',N'Ц')
    UPDATE @returntable SET String = REPLACE(String,'\u0427',N'Ч')
    UPDATE @returntable SET String = REPLACE(String,'\u0428',N'Ш')
    UPDATE @returntable SET String = REPLACE(String,'\u0429',N'Щ')
    UPDATE @returntable SET String = REPLACE(String,'\u042a',N'Ъ')
    UPDATE @returntable SET String = REPLACE(String,'\u042b',N'Ы')
    UPDATE @returntable SET String = REPLACE(String,'\u042c',N'Ь')
    UPDATE @returntable SET String = REPLACE(String,'\u042d',N'Э')
    UPDATE @returntable SET String = REPLACE(String,'\u042e',N'Ю')
    UPDATE @returntable SET String = REPLACE(String,'\u042f',N'Я')

    RETURN
END
