PRINT 'Populate CarBrand table...'
IF NOT EXISTS (SELECT 1 FROM dbo.CarBrand) BEGIN
    SET IDENTITY_INSERT [dbo].[CarBrand] ON
    INSERT INTO [dbo].[CarBrand]
               ([CarBrandId]
               ,[Name])
    SELECT 1,N'Acura' UNION ALL
    SELECT 139,N'Adler' UNION ALL
    SELECT 3,N'Alfa Romeo' UNION ALL
    SELECT 166,N'Alpina' UNION ALL
    SELECT 168,N'Aro' UNION ALL
    SELECT 98,N'Asia' UNION ALL
    SELECT 94,N'Aston Martin' UNION ALL
    SELECT 2,N'Audi' UNION ALL
    SELECT 110,N'Austin' UNION ALL
    SELECT 88,N'Avia' UNION ALL
    SELECT 76,N'Barkas' UNION ALL
    SELECT 93,N'BAW' UNION ALL
    SELECT 4,N'Bentley' UNION ALL
    SELECT 5,N'BMW' UNION ALL
    SELECT 6,N'Brilliance' UNION ALL
    SELECT 130,N'Bugatti' UNION ALL
    SELECT 7,N'Buick' UNION ALL
    SELECT 115,N'BYD' UNION ALL
    SELECT 8,N'Cadillac' UNION ALL
    SELECT 153,N'Changan' UNION ALL
    SELECT 9,N'Chery' UNION ALL
    SELECT 10,N'Chevrolet' UNION ALL
    SELECT 11,N'Chrysler' UNION ALL
    SELECT 12,N'Citroen' UNION ALL
    SELECT 13,N'Dacia' UNION ALL
    SELECT 14,N'Daewoo' UNION ALL
    SELECT 91,N'DAF' UNION ALL
    SELECT 15,N'Daihatsu' UNION ALL
    SELECT 151,N'Datsun' UNION ALL
    SELECT 148,N'Derways' UNION ALL
    SELECT 16,N'Dodge' UNION ALL
    SELECT 170,N'Dongfeng' UNION ALL
    SELECT 101,N'Eagle' UNION ALL
    SELECT 87,N'FAW' UNION ALL
    SELECT 17,N'Ferrari' UNION ALL
    SELECT 18,N'Fiat' UNION ALL
    SELECT 19,N'Ford' UNION ALL
    SELECT 141,N'Foton' UNION ALL
    SELECT 122,N'FSO' UNION ALL
    SELECT 20,N'Geely' UNION ALL
    SELECT 21,N'GMC' UNION ALL
    SELECT 22,N'Great Wall' UNION ALL
    SELECT 77,N'Hafei' UNION ALL
    SELECT 156,N'Haima' UNION ALL
    SELECT 23,N'Honda' UNION ALL
    SELECT 24,N'Hummer' UNION ALL
    SELECT 25,N'Hyundai' UNION ALL
    SELECT 26,N'Infiniti' UNION ALL
    SELECT 100,N'Intrall' UNION ALL
    SELECT 27,N'Iran Khordo' UNION ALL
    SELECT 28,N'Isuzu' UNION ALL
    SELECT 71,N'Iveco' UNION ALL
    SELECT 29,N'JAC' UNION ALL
    SELECT 30,N'Jaguar' UNION ALL
    SELECT 31,N'Jeep' UNION ALL
    SELECT 163,N'Jiangling' UNION ALL
    SELECT 32,N'Kia' UNION ALL
    SELECT 79,N'Lamborghini' UNION ALL
    SELECT 33,N'Lancia' UNION ALL
    SELECT 34,N'Land Rover' UNION ALL
    SELECT 158,N'LDV' UNION ALL
    SELECT 35,N'Lexus' UNION ALL
    SELECT 99,N'Lifan' UNION ALL
    SELECT 36,N'Lincoln' UNION ALL
    SELECT 37,N'Maserati' UNION ALL
    SELECT 38,N'Maybach' UNION ALL
    SELECT 39,N'Mazda' UNION ALL
    SELECT 40,N'MCC Smart' UNION ALL
    SELECT 41,N'Mercedes' UNION ALL
    SELECT 42,N'Mercury' UNION ALL
    SELECT 78,N'MG' UNION ALL
    SELECT 43,N'Mini' UNION ALL
    SELECT 44,N'Mitsubishi' UNION ALL
    SELECT 118,N'Mudan' UNION ALL
    SELECT 45,N'Nissan' UNION ALL
    SELECT 133,N'Nysa' UNION ALL
    SELECT 46,N'Oldsmobile' UNION ALL
    SELECT 144,N'Oltcit' UNION ALL
    SELECT 47,N'Opel' UNION ALL
    SELECT 48,N'Peugeot' UNION ALL
    SELECT 146,N'Pinzgauer' UNION ALL
    SELECT 75,N'Plymouth' UNION ALL
    SELECT 49,N'Pontiac' UNION ALL
    SELECT 50,N'Porsche' UNION ALL
    SELECT 51,N'Proton' UNION ALL
    SELECT 52,N'Renault' UNION ALL
    SELECT 108,N'Rolls-Royce' UNION ALL
    SELECT 53,N'Rover' UNION ALL
    SELECT 54,N'Saab' UNION ALL
    SELECT 161,N'Saipa' UNION ALL
    SELECT 97,N'Santana' UNION ALL
    SELECT 55,N'Saturn' UNION ALL
    SELECT 80,N'Scion' UNION ALL
    SELECT 56,N'Seat' UNION ALL
    SELECT 136,N'Shuanghuan' UNION ALL
    SELECT 72,N'Simca-Chrysler' UNION ALL
    SELECT 57,N'Skoda' UNION ALL
    SELECT 109,N'Spyker' UNION ALL
    SELECT 58,N'Ssang Yong' UNION ALL
    SELECT 172,N'Steyr' UNION ALL
    SELECT 59,N'Subaru' UNION ALL
    SELECT 60,N'Suzuki' UNION ALL
    SELECT 171,N'Syrena' UNION ALL
    SELECT 95,N'Talbot' UNION ALL
    SELECT 128,N'Tata' UNION ALL
    SELECT 112,N'Tesla' UNION ALL
    SELECT 61,N'Toyota' UNION ALL
    SELECT 96,N'Trabant' UNION ALL
    SELECT 169,N'Vauxhall' UNION ALL
    SELECT 62,N'Volkswagen' UNION ALL
    SELECT 63,N'Volvo' UNION ALL
    SELECT 167,N'Vortex' UNION ALL
    SELECT 81,N'Wartburg' UNION ALL
    SELECT 105,N'Zastava' UNION ALL
    SELECT 111,N'Zotye' UNION ALL
    SELECT 125,N'Zuk' UNION ALL
    SELECT 119,N'ZX' UNION ALL
    SELECT 65,N'ВАЗ' UNION ALL
    SELECT 66,N'ГАЗ' UNION ALL
    SELECT 137,N'ЕрАЗ' UNION ALL
    SELECT 67,N'ЗАЗ' UNION ALL
    SELECT 73,N'ИЖ' UNION ALL
    SELECT 74,N'ЛуАЗ' UNION ALL
    SELECT 68,N'Москвич' UNION ALL
    SELECT 92,N'РАФ' UNION ALL
    SELECT 102,N'СМЗ' UNION ALL
    SELECT 142,N'ТагАЗ' UNION ALL
    SELECT 70,N'УАЗ' UNION ALL
    SELECT 173,N'Прицепы'
    SET IDENTITY_INSERT [dbo].[CarBrand] OFF
END