PRINT 'Populate CarModel table...'
IF NOT EXISTS (SELECT 1 FROM dbo.CarModel) BEGIN
    INSERT INTO [dbo].[CarModel]
                   ([CarBrandId]
                   ,[Name])
    SELECT 1,N'CL' UNION ALL
    SELECT 1,N'ILX' UNION ALL
    SELECT 1,N'MDX' UNION ALL
    SELECT 1,N'RDX' UNION ALL
    SELECT 1,N'RL' UNION ALL
    SELECT 1,N'RSX' UNION ALL
    SELECT 1,N'SLX' UNION ALL
    SELECT 1,N'TL' UNION ALL
    SELECT 1,N'TLX' UNION ALL
    SELECT 1,N'TSX' UNION ALL
    SELECT 1,N'Vigor' UNION ALL
    SELECT 1,N'ZDX' UNION ALL
    SELECT 10,N'Alero' UNION ALL
    SELECT 10,N'Astro Van' UNION ALL
    SELECT 10,N'Avalanche' UNION ALL
    SELECT 10,N'Aveo' UNION ALL
    SELECT 10,N'Beretta' UNION ALL
    SELECT 10,N'Blazer' UNION ALL
    SELECT 10,N'C1500' UNION ALL
    SELECT 10,N'Camaro' UNION ALL
    SELECT 10,N'Caprice' UNION ALL
    SELECT 10,N'Captiva' UNION ALL
    SELECT 10,N'Cavalier' UNION ALL
    SELECT 10,N'Celebrity' UNION ALL
    SELECT 10,N'Cobalt' UNION ALL
    SELECT 10,N'Colorado' UNION ALL
    SELECT 10,N'Corsica' UNION ALL
    SELECT 10,N'Corvette' UNION ALL
    SELECT 10,N'Cruze' UNION ALL
    SELECT 10,N'CSV CR8' UNION ALL
    SELECT 10,N'Epica' UNION ALL
    SELECT 10,N'Equinox' UNION ALL
    SELECT 10,N'Express' UNION ALL
    SELECT 10,N'Geo Storm' UNION ALL
    SELECT 10,N'HHR' UNION ALL
    SELECT 10,N'Impala' UNION ALL
    SELECT 10,N'Kalos' UNION ALL
    SELECT 10,N'Lacetti' UNION ALL
    SELECT 10,N'Lanos' UNION ALL
    SELECT 10,N'Lumina' UNION ALL
    SELECT 10,N'Malibu' UNION ALL
    SELECT 10,N'Matiz' UNION ALL
    SELECT 10,N'Metro' UNION ALL
    SELECT 10,N'Monte Carlo' UNION ALL
    SELECT 10,N'Niva' UNION ALL
    SELECT 10,N'Nova' UNION ALL
    SELECT 10,N'Nubira' UNION ALL
    SELECT 10,N'Optra' UNION ALL
    SELECT 10,N'Orlando' UNION ALL
    SELECT 10,N'Prizm' UNION ALL
    SELECT 10,N'Rezzo' UNION ALL
    SELECT 10,N'Shevi-Van' UNION ALL
    SELECT 10,N'Silver' UNION ALL
    SELECT 10,N'Spark' UNION ALL
    SELECT 10,N'Spectrum' UNION ALL
    SELECT 10,N'Sprint' UNION ALL
    SELECT 10,N'Suburban' UNION ALL
    SELECT 10,N'Tahoe' UNION ALL
    SELECT 10,N'Tracker' UNION ALL
    SELECT 10,N'Trail Blazer' UNION ALL
    SELECT 10,N'Trans Sport' UNION ALL
    SELECT 10,N'Trax' UNION ALL
    SELECT 10,N'Uplander' UNION ALL
    SELECT 10,N'Van' UNION ALL
    SELECT 10,N'Venture' UNION ALL
    SELECT 10,N'Volt' UNION ALL
    SELECT 10,N'Yukon' UNION ALL
    SELECT 10,N'Zafira' UNION ALL
    SELECT 100,N'Lublin' UNION ALL
    SELECT 101,N'Premier' UNION ALL
    SELECT 102,N'C-3А' UNION ALL
    SELECT 102,N'C-3АБ' UNION ALL
    SELECT 102,N'С-3АМ' UNION ALL
    SELECT 102,N'С-3Д' UNION ALL
    SELECT 105,N'10' UNION ALL
    SELECT 105,N'101' UNION ALL
    SELECT 105,N'Cabrio' UNION ALL
    SELECT 105,N'Florida' UNION ALL
    SELECT 105,N'Koral' UNION ALL
    SELECT 105,N'Skala' UNION ALL
    SELECT 105,N'Yugo' UNION ALL
    SELECT 108,N'Ghost' UNION ALL
    SELECT 108,N'Phantom' UNION ALL
    SELECT 108,N'Silver Spirit' UNION ALL
    SELECT 109,N'C8' UNION ALL
    SELECT 11,N'200' UNION ALL
    SELECT 11,N'300' UNION ALL
    SELECT 11,N'Aspen' UNION ALL
    SELECT 11,N'Caravan' UNION ALL
    SELECT 11,N'Cirrus' UNION ALL
    SELECT 11,N'Concorde' UNION ALL
    SELECT 11,N'Crossfire' UNION ALL
    SELECT 11,N'Daytona' UNION ALL
    SELECT 11,N'Grand Voyager' UNION ALL
    SELECT 11,N'GTS' UNION ALL
    SELECT 11,N'Imperial' UNION ALL
    SELECT 11,N'Intrepid' UNION ALL
    SELECT 11,N'Le Baron' UNION ALL
    SELECT 11,N'LHS' UNION ALL
    SELECT 11,N'Neon' UNION ALL
    SELECT 11,N'New Yorker' UNION ALL
    SELECT 11,N'Pacifica' UNION ALL
    SELECT 11,N'PT Cruiser' UNION ALL
    SELECT 11,N'Saratoga' UNION ALL
    SELECT 11,N'Sebring' UNION ALL
    SELECT 11,N'Stratus' UNION ALL
    SELECT 11,N'Town&Country' UNION ALL
    SELECT 11,N'Viper' UNION ALL
    SELECT 11,N'Vision' UNION ALL
    SELECT 11,N'Voyager' UNION ALL
    SELECT 110,N'Allegro' UNION ALL
    SELECT 110,N'Princess' UNION ALL
    SELECT 111,N'2008' UNION ALL
    SELECT 111,N'M300' UNION ALL
    SELECT 111,N'V10' UNION ALL
    SELECT 111,N'Z200' UNION ALL
    SELECT 111,N'Z300' UNION ALL
    SELECT 112,N'Model S' UNION ALL
    SELECT 115,N'E6' UNION ALL
    SELECT 115,N'F0' UNION ALL
    SELECT 115,N'F3' UNION ALL
    SELECT 115,N'F6' UNION ALL
    SELECT 115,N'Flyer' UNION ALL
    SELECT 115,N'G3' UNION ALL
    SELECT 115,N'G6' UNION ALL
    SELECT 115,N'L3' UNION ALL
    SELECT 115,N'M6' UNION ALL
    SELECT 115,N'S6' UNION ALL
    SELECT 118,N'MD' UNION ALL
    SELECT 119,N'Admiral' UNION ALL
    SELECT 119,N'Chanling' UNION ALL
    SELECT 119,N'Grand Tiger' UNION ALL
    SELECT 119,N'Landmark' UNION ALL
    SELECT 12,N'2 CV' UNION ALL
    SELECT 12,N'AX' UNION ALL
    SELECT 12,N'Berlingo' UNION ALL
    SELECT 12,N'BX' UNION ALL
    SELECT 12,N'C-Crosser' UNION ALL
    SELECT 12,N'C-ELYS\u00c9E' UNION ALL
    SELECT 12,N'C1' UNION ALL
    SELECT 12,N'C2' UNION ALL
    SELECT 12,N'C25' UNION ALL
    SELECT 12,N'C3' UNION ALL
    SELECT 12,N'C3 Picasso' UNION ALL
    SELECT 12,N'C4' UNION ALL
    SELECT 12,N'C4 AirCross' UNION ALL
    SELECT 12,N'C4 Grand Picasso' UNION ALL
    SELECT 12,N'C4 Picasso' UNION ALL
    SELECT 12,N'C5' UNION ALL
    SELECT 12,N'C6' UNION ALL
    SELECT 12,N'C8' UNION ALL
    SELECT 12,N'CX' UNION ALL
    SELECT 12,N'DS3' UNION ALL
    SELECT 12,N'DS4' UNION ALL
    SELECT 12,N'DS5' UNION ALL
    SELECT 12,N'Evasion' UNION ALL
    SELECT 12,N'GSA' UNION ALL
    SELECT 12,N'Jumper' UNION ALL
    SELECT 12,N'Jumpy' UNION ALL
    SELECT 12,N'Nemo' UNION ALL
    SELECT 12,N'Saxo' UNION ALL
    SELECT 12,N'SM' UNION ALL
    SELECT 12,N'Visa' UNION ALL
    SELECT 12,N'Xantia' UNION ALL
    SELECT 12,N'XM' UNION ALL
    SELECT 12,N'Xsara' UNION ALL
    SELECT 12,N'Xsara Picasso' UNION ALL
    SELECT 12,N'ZX' UNION ALL
    SELECT 122,N'Polonez' UNION ALL
    SELECT 122,N'Warszawa' UNION ALL
    SELECT 125,N'А05' UNION ALL
    SELECT 125,N'А06' UNION ALL
    SELECT 125,N'АН' UNION ALL
    SELECT 128,N'Aria' UNION ALL
    SELECT 128,N'Indica' UNION ALL
    SELECT 128,N'Indigo' UNION ALL
    SELECT 128,N'Manza' UNION ALL
    SELECT 128,N'Nano' UNION ALL
    SELECT 128,N'Safari Dicor' UNION ALL
    SELECT 128,N'Safari Storme' UNION ALL
    SELECT 128,N'Sumo Gold' UNION ALL
    SELECT 128,N'Sumo Grande' UNION ALL
    SELECT 128,N'Telcoline' UNION ALL
    SELECT 128,N'Venture' UNION ALL
    SELECT 128,N'Vista' UNION ALL
    SELECT 128,N'Xenon XT' UNION ALL
    SELECT 13,N'1300' UNION ALL
    SELECT 13,N'1310' UNION ALL
    SELECT 13,N'Duster' UNION ALL
    SELECT 13,N'Lodgy' UNION ALL
    SELECT 13,N'Logan' UNION ALL
    SELECT 13,N'Pick Up' UNION ALL
    SELECT 13,N'Sandero' UNION ALL
    SELECT 130,N'Veyron' UNION ALL
    SELECT 133,N'501' UNION ALL
    SELECT 133,N'521' UNION ALL
    SELECT 133,N'522' UNION ALL
    SELECT 136,N'CEO' UNION ALL
    SELECT 136,N'Laibao' UNION ALL
    SELECT 136,N'Noble' UNION ALL
    SELECT 137,N'3730' UNION ALL
    SELECT 137,N'762' UNION ALL
    SELECT 139,N'Diplomat' UNION ALL
    SELECT 139,N'Standard' UNION ALL
    SELECT 139,N'Trumpf Junior' UNION ALL
    SELECT 139,N'Trumpf Karman' UNION ALL
    SELECT 14,N'Espero' UNION ALL
    SELECT 14,N'Evanda' UNION ALL
    SELECT 14,N'Gentra' UNION ALL
    SELECT 14,N'Kalos' UNION ALL
    SELECT 14,N'Korando' UNION ALL
    SELECT 14,N'Lacetti' UNION ALL
    SELECT 14,N'Lanos' UNION ALL
    SELECT 14,N'Leganza' UNION ALL
    SELECT 14,N'Magnus' UNION ALL
    SELECT 14,N'Matiz' UNION ALL
    SELECT 14,N'Musso' UNION ALL
    SELECT 14,N'Nexia' UNION ALL
    SELECT 14,N'Nubira' UNION ALL
    SELECT 14,N'Rezzo' UNION ALL
    SELECT 14,N'Tacuma' UNION ALL
    SELECT 14,N'Tico' UNION ALL
    SELECT 141,N'Aumark' UNION ALL
    SELECT 141,N'Forland' UNION ALL
    SELECT 141,N'Ollin' UNION ALL
    SELECT 141,N'Saga' UNION ALL
    SELECT 141,N'Sup' UNION ALL
    SELECT 141,N'View' UNION ALL
    SELECT 142,N'Aquila' UNION ALL
    SELECT 144,N'Club' UNION ALL
    SELECT 144,N'Special' UNION ALL
    SELECT 146,N'710K' UNION ALL
    SELECT 146,N'710M' UNION ALL
    SELECT 146,N'712K' UNION ALL
    SELECT 146,N'712M' UNION ALL
    SELECT 146,N'716' UNION ALL
    SELECT 148,N'Antelope' UNION ALL
    SELECT 148,N'Aurora' UNION ALL
    SELECT 148,N'Cowboy' UNION ALL
    SELECT 148,N'Land Crown' UNION ALL
    SELECT 148,N'Plutus' UNION ALL
    SELECT 148,N'Saladin' UNION ALL
    SELECT 148,N'Shuttle' UNION ALL
    SELECT 15,N'Applause' UNION ALL
    SELECT 15,N'Charade' UNION ALL
    SELECT 15,N'Charmant' UNION ALL
    SELECT 15,N'Copen' UNION ALL
    SELECT 15,N'Cuore' UNION ALL
    SELECT 15,N'Feroza/Sportrak' UNION ALL
    SELECT 15,N'Freeclimber' UNION ALL
    SELECT 15,N'Gran Move' UNION ALL
    SELECT 15,N'Hijet' UNION ALL
    SELECT 15,N'Materia' UNION ALL
    SELECT 15,N'Move' UNION ALL
    SELECT 15,N'Rocky/Fourtrak' UNION ALL
    SELECT 15,N'Sirion' UNION ALL
    SELECT 15,N'Terios' UNION ALL
    SELECT 15,N'Trevis' UNION ALL
    SELECT 15,N'YRV' UNION ALL
    SELECT 151,N'1000' UNION ALL
    SELECT 151,N'Bluebird 310' UNION ALL
    SELECT 151,N'Go' UNION ALL
    SELECT 151,N'Go+' UNION ALL
    SELECT 151,N'mi-DO' UNION ALL
    SELECT 151,N'on-DO' UNION ALL
    SELECT 151,N'Sunny B10' UNION ALL
    SELECT 153,N'CS35' UNION ALL
    SELECT 153,N'Eado' UNION ALL
    SELECT 153,N'Raeton' UNION ALL
    SELECT 156,N'1' UNION ALL
    SELECT 156,N'2' UNION ALL
    SELECT 156,N'3' UNION ALL
    SELECT 156,N'7' UNION ALL
    SELECT 156,N'Family' UNION ALL
    SELECT 156,N'Freema' UNION ALL
    SELECT 156,N'Fstar' UNION ALL
    SELECT 156,N'Happin' UNION ALL
    SELECT 156,N'M3' UNION ALL
    SELECT 156,N'M5' UNION ALL
    SELECT 156,N'M8' UNION ALL
    SELECT 156,N'S5' UNION ALL
    SELECT 156,N'S7' UNION ALL
    SELECT 158,N'Convoy' UNION ALL
    SELECT 158,N'Maxus' UNION ALL
    SELECT 158,N'Pilot' UNION ALL
    SELECT 16,N'1500' UNION ALL
    SELECT 16,N'2500' UNION ALL
    SELECT 16,N'3500' UNION ALL
    SELECT 16,N'Aspen' UNION ALL
    SELECT 16,N'Avenger' UNION ALL
    SELECT 16,N'Caliber' UNION ALL
    SELECT 16,N'Caravan' UNION ALL
    SELECT 16,N'Challenger' UNION ALL
    SELECT 16,N'Charger' UNION ALL
    SELECT 16,N'Colt' UNION ALL
    SELECT 16,N'D150' UNION ALL
    SELECT 16,N'D250' UNION ALL
    SELECT 16,N'D350' UNION ALL
    SELECT 16,N'Dakota' UNION ALL
    SELECT 16,N'Dart' UNION ALL
    SELECT 16,N'Daytona' UNION ALL
    SELECT 16,N'Durango' UNION ALL
    SELECT 16,N'Durango Hybrid' UNION ALL
    SELECT 16,N'Dynasty' UNION ALL
    SELECT 16,N'Grand Caravan' UNION ALL
    SELECT 16,N'Intrepid' UNION ALL
    SELECT 16,N'Journey' UNION ALL
    SELECT 16,N'Magnum' UNION ALL
    SELECT 16,N'Monaco' UNION ALL
    SELECT 16,N'Neon' UNION ALL
    SELECT 16,N'Nitro' UNION ALL
    SELECT 16,N'Omni' UNION ALL
    SELECT 16,N'Ram' UNION ALL
    SELECT 16,N'Roadtrek' UNION ALL
    SELECT 16,N'Shadow' UNION ALL
    SELECT 16,N'Spirit' UNION ALL
    SELECT 16,N'Stealth' UNION ALL
    SELECT 16,N'Stratus' UNION ALL
    SELECT 16,N'Van' UNION ALL
    SELECT 16,N'Viper' UNION ALL
    SELECT 16,N'W150' UNION ALL
    SELECT 16,N'W250' UNION ALL
    SELECT 16,N'W350' UNION ALL
    SELECT 161,N'111' UNION ALL
    SELECT 161,N'131' UNION ALL
    SELECT 161,N'132' UNION ALL
    SELECT 161,N'141' UNION ALL
    SELECT 161,N'151' UNION ALL
    SELECT 161,N'2' UNION ALL
    SELECT 161,N'Cerato' UNION ALL
    SELECT 161,N'CS35' UNION ALL
    SELECT 161,N'Eado' UNION ALL
    SELECT 161,N'H230' UNION ALL
    SELECT 161,N'H320' UNION ALL
    SELECT 161,N'H330' UNION ALL
    SELECT 161,N'Kolius' UNION ALL
    SELECT 161,N'Padra' UNION ALL
    SELECT 161,N'S300' UNION ALL
    SELECT 161,N'Saina' UNION ALL
    SELECT 161,N'Tiba' UNION ALL
    SELECT 161,N'Tondar' UNION ALL
    SELECT 161,N'V5' UNION ALL
    SELECT 163,N'Landwind' UNION ALL
    SELECT 166,N'B3' UNION ALL
    SELECT 166,N'B4' UNION ALL
    SELECT 166,N'B5' UNION ALL
    SELECT 166,N'B6' UNION ALL
    SELECT 166,N'B7' UNION ALL
    SELECT 166,N'D3' UNION ALL
    SELECT 166,N'D4' UNION ALL
    SELECT 166,N'D5' UNION ALL
    SELECT 166,N'XD3' UNION ALL
    SELECT 167,N'Corda' UNION ALL
    SELECT 167,N'Estina' UNION ALL
    SELECT 167,N'Tingo' UNION ALL
    SELECT 168,N'240' UNION ALL
    SELECT 168,N'243' UNION ALL
    SELECT 168,N'244' UNION ALL
    SELECT 168,N'246' UNION ALL
    SELECT 168,N'266' UNION ALL
    SELECT 168,N'323' UNION ALL
    SELECT 168,N'324' UNION ALL
    SELECT 168,N'328' UNION ALL
    SELECT 168,N'330' UNION ALL
    SELECT 169,N'Adam' UNION ALL
    SELECT 169,N'Ampera' UNION ALL
    SELECT 169,N'Antara' UNION ALL
    SELECT 169,N'Astra' UNION ALL
    SELECT 169,N'Cascada' UNION ALL
    SELECT 169,N'Combo Tour' UNION ALL
    SELECT 169,N'Corsa' UNION ALL
    SELECT 169,N'Insignia' UNION ALL
    SELECT 169,N'Meriva' UNION ALL
    SELECT 169,N'Mokka' UNION ALL
    SELECT 169,N'Viva' UNION ALL
    SELECT 169,N'Vivaro' UNION ALL
    SELECT 169,N'VXR8' UNION ALL
    SELECT 169,N'Zafira Tourer' UNION ALL
    SELECT 17,N'150 GTO' UNION ALL
    SELECT 17,N'250 GTO' UNION ALL
    SELECT 17,N'328' UNION ALL
    SELECT 17,N'330' UNION ALL
    SELECT 17,N'360 Modena' UNION ALL
    SELECT 17,N'365' UNION ALL
    SELECT 17,N'456 GT/GTA' UNION ALL
    SELECT 17,N'512 M' UNION ALL
    SELECT 17,N'550 Maranello' UNION ALL
    SELECT 17,N'575 Maranello' UNION ALL
    SELECT 17,N'626' UNION ALL
    SELECT 17,N'California' UNION ALL
    SELECT 17,N'F355 Berlinetta' UNION ALL
    SELECT 17,N'F40' UNION ALL
    SELECT 17,N'F50' UNION ALL
    SELECT 17,N'Mondial' UNION ALL
    SELECT 170,N'H30' UNION ALL
    SELECT 170,N'S30' UNION ALL
    SELECT 171,N'100' UNION ALL
    SELECT 171,N'101' UNION ALL
    SELECT 171,N'102' UNION ALL
    SELECT 171,N'103' UNION ALL
    SELECT 171,N'104' UNION ALL
    SELECT 171,N'105' UNION ALL
    SELECT 172,N'220' UNION ALL
    SELECT 172,N'50' UNION ALL
    SELECT 172,N'55' UNION ALL
    SELECT 18,N'124' UNION ALL
    SELECT 18,N'125' UNION ALL
    SELECT 18,N'126' UNION ALL
    SELECT 18,N'127' UNION ALL
    SELECT 18,N'128' UNION ALL
    SELECT 18,N'130' UNION ALL
    SELECT 18,N'131' UNION ALL
    SELECT 18,N'238' UNION ALL
    SELECT 18,N'500' UNION ALL
    SELECT 18,N'Albea' UNION ALL
    SELECT 18,N'Argenta' UNION ALL
    SELECT 18,N'Barchetta' UNION ALL
    SELECT 18,N'Brava' UNION ALL
    SELECT 18,N'Bravo' UNION ALL
    SELECT 18,N'Cinquecento' UNION ALL
    SELECT 18,N'Coupe' UNION ALL
    SELECT 18,N'Croma' UNION ALL
    SELECT 18,N'Dino' UNION ALL
    SELECT 18,N'Doblo' UNION ALL
    SELECT 18,N'Ducato' UNION ALL
    SELECT 18,N'Fiorino' UNION ALL
    SELECT 18,N'Freemont' UNION ALL
    SELECT 18,N'Grande Punto' UNION ALL
    SELECT 18,N'Idea' UNION ALL
    SELECT 18,N'Lancia' UNION ALL
    SELECT 18,N'Linea' UNION ALL
    SELECT 18,N'Marea' UNION ALL
    SELECT 18,N'Marengo' UNION ALL
    SELECT 18,N'Multipla' UNION ALL
    SELECT 18,N'Palio' UNION ALL
    SELECT 18,N'Panda' UNION ALL
    SELECT 18,N'Punto' UNION ALL
    SELECT 18,N'Qubo' UNION ALL
    SELECT 18,N'Regata' UNION ALL
    SELECT 18,N'Ritmo' UNION ALL
    SELECT 18,N'Scudo' UNION ALL
    SELECT 18,N'Sedici' UNION ALL
    SELECT 18,N'Seicento' UNION ALL
    SELECT 18,N'Siena' UNION ALL
    SELECT 18,N'Spider Europa' UNION ALL
    SELECT 18,N'Stilo' UNION ALL
    SELECT 18,N'Strada' UNION ALL
    SELECT 18,N'Tempra' UNION ALL
    SELECT 18,N'Tipo' UNION ALL
    SELECT 18,N'Ulysse' UNION ALL
    SELECT 18,N'Uno' UNION ALL
    SELECT 18,N'X 1/9' UNION ALL
    SELECT 19,N'Aerostar' UNION ALL
    SELECT 19,N'B-Max' UNION ALL
    SELECT 19,N'Bronco' UNION ALL
    SELECT 19,N'C-Max' UNION ALL
    SELECT 19,N'Capri' UNION ALL
    SELECT 19,N'Contour' UNION ALL
    SELECT 19,N'Cougar' UNION ALL
    SELECT 19,N'Courier' UNION ALL
    SELECT 19,N'Crown Victoria' UNION ALL
    SELECT 19,N'Econoline' UNION ALL
    SELECT 19,N'Econovan' UNION ALL
    SELECT 19,N'EcoSport' UNION ALL
    SELECT 19,N'Edge' UNION ALL
    SELECT 19,N'Escape' UNION ALL
    SELECT 19,N'Escort' UNION ALL
    SELECT 19,N'Excursion' UNION ALL
    SELECT 19,N'Expedition' UNION ALL
    SELECT 19,N'Explorer' UNION ALL
    SELECT 19,N'Express' UNION ALL
    SELECT 19,N'F150' UNION ALL
    SELECT 19,N'F250' UNION ALL
    SELECT 19,N'F350' UNION ALL
    SELECT 19,N'Fairlane' UNION ALL
    SELECT 19,N'Fairmont' UNION ALL
    SELECT 19,N'Falcon' UNION ALL
    SELECT 19,N'Fiesta' UNION ALL
    SELECT 19,N'Flex' UNION ALL
    SELECT 19,N'Focus' UNION ALL
    SELECT 19,N'Freestar' UNION ALL
    SELECT 19,N'Freestyle' UNION ALL
    SELECT 19,N'Fusion' UNION ALL
    SELECT 19,N'Galaxy' UNION ALL
    SELECT 19,N'Granada' UNION ALL
    SELECT 19,N'Grand C-Max' UNION ALL
    SELECT 19,N'GT' UNION ALL
    SELECT 19,N'Ka' UNION ALL
    SELECT 19,N'Kuga' UNION ALL
    SELECT 19,N'Maverick' UNION ALL
    SELECT 19,N'Mercury' UNION ALL
    SELECT 19,N'Model 40A' UNION ALL
    SELECT 19,N'Mondeo' UNION ALL
    SELECT 19,N'Mustang' UNION ALL
    SELECT 19,N'Orion' UNION ALL
    SELECT 19,N'Probe' UNION ALL
    SELECT 19,N'Puma' UNION ALL
    SELECT 19,N'Ranger' UNION ALL
    SELECT 19,N'S-Max' UNION ALL
    SELECT 19,N'Scorpio' UNION ALL
    SELECT 19,N'Sierra' UNION ALL
    SELECT 19,N'Sportka' UNION ALL
    SELECT 19,N'Streetka' UNION ALL
    SELECT 19,N'Taunus' UNION ALL
    SELECT 19,N'Taurus' UNION ALL
    SELECT 19,N'Tempo' UNION ALL
    SELECT 19,N'Thunderbird' UNION ALL
    SELECT 19,N'Tourneo' UNION ALL
    SELECT 19,N'Tourneo Custom' UNION ALL
    SELECT 19,N'Transit' UNION ALL
    SELECT 19,N'Windstar' UNION ALL
    SELECT 2,N'100' UNION ALL
    SELECT 2,N'200' UNION ALL
    SELECT 2,N'50' UNION ALL
    SELECT 2,N'80' UNION ALL
    SELECT 2,N'90' UNION ALL
    SELECT 2,N'A1' UNION ALL
    SELECT 2,N'A2' UNION ALL
    SELECT 2,N'A3' UNION ALL
    SELECT 2,N'A4' UNION ALL
    SELECT 2,N'A5' UNION ALL
    SELECT 2,N'A6' UNION ALL
    SELECT 2,N'A6 Allroad' UNION ALL
    SELECT 2,N'A7' UNION ALL
    SELECT 2,N'A8' UNION ALL
    SELECT 2,N'Cabriolet' UNION ALL
    SELECT 2,N'Coupe' UNION ALL
    SELECT 2,N'Q3' UNION ALL
    SELECT 2,N'Q5' UNION ALL
    SELECT 2,N'Q7' UNION ALL
    SELECT 2,N'R8' UNION ALL
    SELECT 2,N'RS3' UNION ALL
    SELECT 2,N'RS4' UNION ALL
    SELECT 2,N'RS5' UNION ALL
    SELECT 2,N'RS6' UNION ALL
    SELECT 2,N'S3' UNION ALL
    SELECT 2,N'S4' UNION ALL
    SELECT 2,N'S5' UNION ALL
    SELECT 2,N'S6' UNION ALL
    SELECT 2,N'S8' UNION ALL
    SELECT 2,N'TT' UNION ALL
    SELECT 2,N'V8' UNION ALL
    SELECT 20,N'CK' UNION ALL
    SELECT 20,N'EC7' UNION ALL
    SELECT 20,N'Emgrand' UNION ALL
    SELECT 20,N'Emgrand 7' UNION ALL
    SELECT 20,N'Emgrand 8' UNION ALL
    SELECT 20,N'EX7' UNION ALL
    SELECT 20,N'FC' UNION ALL
    SELECT 20,N'LC' UNION ALL
    SELECT 20,N'MK' UNION ALL
    SELECT 20,N'SC7' UNION ALL
    SELECT 21,N'Acadia' UNION ALL
    SELECT 21,N'Envoy' UNION ALL
    SELECT 21,N'Jimmy' UNION ALL
    SELECT 21,N'Safari' UNION ALL
    SELECT 21,N'Savana' UNION ALL
    SELECT 21,N'Sierra' UNION ALL
    SELECT 21,N'Sonoma' UNION ALL
    SELECT 21,N'Syclone' UNION ALL
    SELECT 21,N'Terrain' UNION ALL
    SELECT 21,N'Typhoon' UNION ALL
    SELECT 21,N'Vandura' UNION ALL
    SELECT 21,N'Yukon' UNION ALL
    SELECT 22,N'Deer' UNION ALL
    SELECT 22,N'Florid' UNION ALL
    SELECT 22,N'H3' UNION ALL
    SELECT 22,N'H5' UNION ALL
    SELECT 22,N'H6' UNION ALL
    SELECT 22,N'Hover' UNION ALL
    SELECT 22,N'M4' UNION ALL
    SELECT 22,N'Pegasus' UNION ALL
    SELECT 22,N'Peri' UNION ALL
    SELECT 22,N'Safe' UNION ALL
    SELECT 22,N'Sing' UNION ALL
    SELECT 22,N'Voleex C30' UNION ALL
    SELECT 22,N'Wingle' UNION ALL
    SELECT 23,N'Accord' UNION ALL
    SELECT 23,N'Aerodeck' UNION ALL
    SELECT 23,N'City' UNION ALL
    SELECT 23,N'Civic' UNION ALL
    SELECT 23,N'Concerto' UNION ALL
    SELECT 23,N'CR-V' UNION ALL
    SELECT 23,N'CR-Z' UNION ALL
    SELECT 23,N'Crosstour' UNION ALL
    SELECT 23,N'CRX' UNION ALL
    SELECT 23,N'Element' UNION ALL
    SELECT 23,N'Fit' UNION ALL
    SELECT 23,N'FR-V' UNION ALL
    SELECT 23,N'HR-V' UNION ALL
    SELECT 23,N'Insight' UNION ALL
    SELECT 23,N'Integra' UNION ALL
    SELECT 23,N'Jazz' UNION ALL
    SELECT 23,N'Legend' UNION ALL
    SELECT 23,N'Logo' UNION ALL
    SELECT 23,N'NSX' UNION ALL
    SELECT 23,N'Odyssey' UNION ALL
    SELECT 23,N'Passport' UNION ALL
    SELECT 23,N'Pilot' UNION ALL
    SELECT 23,N'Prelude' UNION ALL
    SELECT 23,N'Ridgeline' UNION ALL
    SELECT 23,N'S1000' UNION ALL
    SELECT 23,N'S2000' UNION ALL
    SELECT 23,N'Shuttle' UNION ALL
    SELECT 23,N'Stream' UNION ALL
    SELECT 23,N'Vigor' UNION ALL
    SELECT 24,N'H1' UNION ALL
    SELECT 24,N'H2' UNION ALL
    SELECT 24,N'H3' UNION ALL
    SELECT 25,N'Accent' UNION ALL
    SELECT 25,N'Atos' UNION ALL
    SELECT 25,N'Avante' UNION ALL
    SELECT 25,N'Azera' UNION ALL
    SELECT 25,N'Coupe' UNION ALL
    SELECT 25,N'Elantra' UNION ALL
    SELECT 25,N'Equus' UNION ALL
    SELECT 25,N'Excel' UNION ALL
    SELECT 25,N'Galloper' UNION ALL
    SELECT 25,N'Genesis' UNION ALL
    SELECT 25,N'Getz' UNION ALL
    SELECT 25,N'Grand Starex' UNION ALL
    SELECT 25,N'Grandeur' UNION ALL
    SELECT 25,N'H 100' UNION ALL
    SELECT 25,N'H 200' UNION ALL
    SELECT 25,N'H-1' UNION ALL
    SELECT 25,N'i10' UNION ALL
    SELECT 25,N'i20' UNION ALL
    SELECT 25,N'i30' UNION ALL
    SELECT 25,N'i40' UNION ALL
    SELECT 25,N'i50' UNION ALL
    SELECT 25,N'ix20' UNION ALL
    SELECT 25,N'ix35' UNION ALL
    SELECT 25,N'ix55' UNION ALL
    SELECT 25,N'Lantra' UNION ALL
    SELECT 25,N'Matrix' UNION ALL
    SELECT 25,N'Maxcruz' UNION ALL
    SELECT 25,N'Pony' UNION ALL
    SELECT 25,N'Porter' UNION ALL
    SELECT 25,N'S-Coupe' UNION ALL
    SELECT 25,N'Santa Fe' UNION ALL
    SELECT 25,N'Santamo' UNION ALL
    SELECT 25,N'Solaris' UNION ALL
    SELECT 25,N'Sonata' UNION ALL
    SELECT 25,N'Starex' UNION ALL
    SELECT 25,N'Terracan' UNION ALL
    SELECT 25,N'Tiburon' UNION ALL
    SELECT 25,N'Trajet' UNION ALL
    SELECT 25,N'Tucson' UNION ALL
    SELECT 25,N'Veloster' UNION ALL
    SELECT 25,N'Veracruz' UNION ALL
    SELECT 25,N'XG 25' UNION ALL
    SELECT 25,N'XG 30' UNION ALL
    SELECT 25,N'XG 350' UNION ALL
    SELECT 26,N'EX' UNION ALL
    SELECT 26,N'FX' UNION ALL
    SELECT 26,N'G' UNION ALL
    SELECT 26,N'JX' UNION ALL
    SELECT 26,N'M' UNION ALL
    SELECT 26,N'Q' UNION ALL
    SELECT 26,N'QX' UNION ALL
    SELECT 27,N'Samand' UNION ALL
    SELECT 28,N'Amigo' UNION ALL
    SELECT 28,N'Aska' UNION ALL
    SELECT 28,N'Axiom' UNION ALL
    SELECT 28,N'Campo' UNION ALL
    SELECT 28,N'D-Max' UNION ALL
    SELECT 28,N'Gemini' UNION ALL
    SELECT 28,N'Midi' UNION ALL
    SELECT 28,N'Pick Up' UNION ALL
    SELECT 28,N'Rodeo' UNION ALL
    SELECT 28,N'Stylus' UNION ALL
    SELECT 28,N'Trooper' UNION ALL
    SELECT 28,N'Vehiсross' UNION ALL
    SELECT 29,N'HFC' UNION ALL
    SELECT 29,N'HK' UNION ALL
    SELECT 29,N'J2' UNION ALL
    SELECT 29,N'MPV' UNION ALL
    SELECT 29,N'Refine' UNION ALL
    SELECT 29,N'Rein' UNION ALL
    SELECT 29,N'S5' UNION ALL
    SELECT 29,N'SRV' UNION ALL
    SELECT 29,N'Tojoy' UNION ALL
    SELECT 3,N'145' UNION ALL
    SELECT 3,N'146' UNION ALL
    SELECT 3,N'147' UNION ALL
    SELECT 3,N'155' UNION ALL
    SELECT 3,N'156' UNION ALL
    SELECT 3,N'159' UNION ALL
    SELECT 3,N'164' UNION ALL
    SELECT 3,N'166' UNION ALL
    SELECT 3,N'33' UNION ALL
    SELECT 3,N'75' UNION ALL
    SELECT 3,N'90' UNION ALL
    SELECT 3,N'Alfetta' UNION ALL
    SELECT 3,N'Brera' UNION ALL
    SELECT 3,N'Giulietta' UNION ALL
    SELECT 3,N'GT' UNION ALL
    SELECT 3,N'GTV' UNION ALL
    SELECT 3,N'MiTo' UNION ALL
    SELECT 3,N'Spider' UNION ALL
    SELECT 30,N'Daimler' UNION ALL
    SELECT 30,N'E-Type' UNION ALL
    SELECT 30,N'F-Type' UNION ALL
    SELECT 30,N'MK II' UNION ALL
    SELECT 30,N'S-Type' UNION ALL
    SELECT 30,N'X-Type' UNION ALL
    SELECT 30,N'XF' UNION ALL
    SELECT 30,N'XJ' UNION ALL
    SELECT 30,N'XK' UNION ALL
    SELECT 30,N'XKR' UNION ALL
    SELECT 31,N'Cherokee' UNION ALL
    SELECT 31,N'CJ' UNION ALL
    SELECT 31,N'Comanche' UNION ALL
    SELECT 31,N'Commander' UNION ALL
    SELECT 31,N'Compass' UNION ALL
    SELECT 31,N'Grand Cherokee' UNION ALL
    SELECT 31,N'Patriot' UNION ALL
    SELECT 31,N'Renegade' UNION ALL
    SELECT 31,N'Wagoneer' UNION ALL
    SELECT 31,N'Willys' UNION ALL
    SELECT 31,N'Wrangler' UNION ALL
    SELECT 32,N'Avella' UNION ALL
    SELECT 32,N'Besta' UNION ALL
    SELECT 32,N'Cadenza' UNION ALL
    SELECT 32,N'Capital' UNION ALL
    SELECT 32,N'Carens' UNION ALL
    SELECT 32,N'Carnival' UNION ALL
    SELECT 32,N'Cee''d' UNION ALL
    SELECT 32,N'Cerato' UNION ALL
    SELECT 32,N'Clarus' UNION ALL
    SELECT 32,N'Elan' UNION ALL
    SELECT 32,N'Forte' UNION ALL
    SELECT 32,N'Joice' UNION ALL
    SELECT 32,N'K2500' UNION ALL
    SELECT 32,N'K2700' UNION ALL
    SELECT 32,N'K3' UNION ALL
    SELECT 32,N'K5' UNION ALL
    SELECT 32,N'K7' UNION ALL
    SELECT 32,N'K9' UNION ALL
    SELECT 32,N'Leo' UNION ALL
    SELECT 32,N'Magentis' UNION ALL
    SELECT 32,N'Mentor' UNION ALL
    SELECT 32,N'Mini' UNION ALL
    SELECT 32,N'Mohave' UNION ALL
    SELECT 32,N'Opirus' UNION ALL
    SELECT 32,N'Optima' UNION ALL
    SELECT 32,N'Picanto' UNION ALL
    SELECT 32,N'Pregio' UNION ALL
    SELECT 32,N'Pride' UNION ALL
    SELECT 32,N'Pro Cee''d' UNION ALL
    SELECT 32,N'Retona' UNION ALL
    SELECT 32,N'Rio' UNION ALL
    SELECT 32,N'Roadster' UNION ALL
    SELECT 32,N'Rocsta' UNION ALL
    SELECT 32,N'Sephia' UNION ALL
    SELECT 32,N'Shuma' UNION ALL
    SELECT 32,N'Sorento' UNION ALL
    SELECT 32,N'Soul' UNION ALL
    SELECT 32,N'Spectra' UNION ALL
    SELECT 32,N'Sportage' UNION ALL
    SELECT 32,N'Vegna' UNION ALL
    SELECT 32,N'Venga' UNION ALL
    SELECT 32,N'X-Trek' UNION ALL
    SELECT 33,N'Beta' UNION ALL
    SELECT 33,N'Dedra' UNION ALL
    SELECT 33,N'Delta' UNION ALL
    SELECT 33,N'Flaminia' UNION ALL
    SELECT 33,N'Fulvia' UNION ALL
    SELECT 33,N'Gamma' UNION ALL
    SELECT 33,N'Kappa' UNION ALL
    SELECT 33,N'Lybra' UNION ALL
    SELECT 33,N'Musa' UNION ALL
    SELECT 33,N'Phedra' UNION ALL
    SELECT 33,N'Prisma' UNION ALL
    SELECT 33,N'Stratos' UNION ALL
    SELECT 33,N'Thema' UNION ALL
    SELECT 33,N'Thesis' UNION ALL
    SELECT 33,N'Ypsilon' UNION ALL
    SELECT 33,N'Zeta' UNION ALL
    SELECT 34,N'Defender' UNION ALL
    SELECT 34,N'Discovery' UNION ALL
    SELECT 34,N'Freelander' UNION ALL
    SELECT 34,N'Range Rover' UNION ALL
    SELECT 34,N'Range Rover Evoque' UNION ALL
    SELECT 34,N'Range Rover Sport' UNION ALL
    SELECT 35,N'CT' UNION ALL
    SELECT 35,N'ES' UNION ALL
    SELECT 35,N'GS' UNION ALL
    SELECT 35,N'GX' UNION ALL
    SELECT 35,N'HS' UNION ALL
    SELECT 35,N'IS' UNION ALL
    SELECT 35,N'LS' UNION ALL
    SELECT 35,N'LX' UNION ALL
    SELECT 35,N'NX' UNION ALL
    SELECT 35,N'RX' UNION ALL
    SELECT 35,N'SC' UNION ALL
    SELECT 36,N'Aviator' UNION ALL
    SELECT 36,N'Blackwood' UNION ALL
    SELECT 36,N'Continental' UNION ALL
    SELECT 36,N'LS' UNION ALL
    SELECT 36,N'Mark LT' UNION ALL
    SELECT 36,N'Mark VII' UNION ALL
    SELECT 36,N'Mark VIII' UNION ALL
    SELECT 36,N'MKS' UNION ALL
    SELECT 36,N'MKT' UNION ALL
    SELECT 36,N'MKX' UNION ALL
    SELECT 36,N'MKZ' UNION ALL
    SELECT 36,N'Navigator' UNION ALL
    SELECT 36,N'Town Car' UNION ALL
    SELECT 36,N'Zephir' UNION ALL
    SELECT 37,N'228' UNION ALL
    SELECT 37,N'3200GT' UNION ALL
    SELECT 37,N'Coupe Cambiocorsa' UNION ALL
    SELECT 37,N'Ghibli' UNION ALL
    SELECT 37,N'GranTurismo' UNION ALL
    SELECT 37,N'M138 Spyder' UNION ALL
    SELECT 37,N'Quattroporte' UNION ALL
    SELECT 38,N'57' UNION ALL
    SELECT 38,N'62' UNION ALL
    SELECT 39,N'121' UNION ALL
    SELECT 39,N'2' UNION ALL
    SELECT 39,N'3' UNION ALL
    SELECT 39,N'323' UNION ALL
    SELECT 39,N'5' UNION ALL
    SELECT 39,N'6' UNION ALL
    SELECT 39,N'626' UNION ALL
    SELECT 39,N'929' UNION ALL
    SELECT 39,N'B1800' UNION ALL
    SELECT 39,N'B2000' UNION ALL
    SELECT 39,N'B2200' UNION ALL
    SELECT 39,N'B2500' UNION ALL
    SELECT 39,N'B2600' UNION ALL
    SELECT 39,N'B3000' UNION ALL
    SELECT 39,N'B3400' UNION ALL
    SELECT 39,N'BT-50' UNION ALL
    SELECT 39,N'Capella' UNION ALL
    SELECT 39,N'CX-5' UNION ALL
    SELECT 39,N'CX-7' UNION ALL
    SELECT 39,N'CX-9' UNION ALL
    SELECT 39,N'Demio' UNION ALL
    SELECT 39,N'E2200' UNION ALL
    SELECT 39,N'Luce' UNION ALL
    SELECT 39,N'Millenia' UNION ALL
    SELECT 39,N'MPV' UNION ALL
    SELECT 39,N'MX-3' UNION ALL
    SELECT 39,N'MX-5' UNION ALL
    SELECT 39,N'MX-6' UNION ALL
    SELECT 39,N'Navajo' UNION ALL
    SELECT 39,N'Premacy' UNION ALL
    SELECT 39,N'Protege' UNION ALL
    SELECT 39,N'RX-7' UNION ALL
    SELECT 39,N'RX-8' UNION ALL
    SELECT 39,N'Tribute' UNION ALL
    SELECT 39,N'Xedos 6' UNION ALL
    SELECT 39,N'Xedos 9' UNION ALL
    SELECT 4,N'Arnage' UNION ALL
    SELECT 4,N'Azure' UNION ALL
    SELECT 4,N'Brooklands' UNION ALL
    SELECT 4,N'Continental' UNION ALL
    SELECT 4,N'Continental GT' UNION ALL
    SELECT 4,N'Flying Spur' UNION ALL
    SELECT 4,N'Mulsanne' UNION ALL
    SELECT 4,N'Turbo R' UNION ALL
    SELECT 40,N'City Coupe' UNION ALL
    SELECT 40,N'Crossblade' UNION ALL
    SELECT 40,N'Forfour' UNION ALL
    SELECT 40,N'Fortwo' UNION ALL
    SELECT 40,N'Roadster' UNION ALL
    SELECT 41,N'MB100' UNION ALL
    SELECT 41,N'SLR' UNION ALL
    SELECT 41,N'SLS AMG' UNION ALL
    SELECT 41,N'Sprinter' UNION ALL
    SELECT 41,N'T1' UNION ALL
    SELECT 41,N'T2' UNION ALL
    SELECT 41,N'Vaneo' UNION ALL
    SELECT 41,N'Vario' UNION ALL
    SELECT 41,N'Viano' UNION ALL
    SELECT 41,N'Vito' UNION ALL
    SELECT 42,N'Capri' UNION ALL
    SELECT 42,N'Colony Park' UNION ALL
    SELECT 42,N'Cougar' UNION ALL
    SELECT 42,N'Grand Marquis' UNION ALL
    SELECT 42,N'Marauder' UNION ALL
    SELECT 42,N'Mariner' UNION ALL
    SELECT 42,N'Milan' UNION ALL
    SELECT 42,N'Montego' UNION ALL
    SELECT 42,N'Monterey' UNION ALL
    SELECT 42,N'Mountaineer' UNION ALL
    SELECT 42,N'Mystique' UNION ALL
    SELECT 42,N'Sable' UNION ALL
    SELECT 42,N'Topaz' UNION ALL
    SELECT 42,N'Tracer' UNION ALL
    SELECT 42,N'Villager' UNION ALL
    SELECT 43,N'1000' UNION ALL
    SELECT 43,N'1300' UNION ALL
    SELECT 43,N'Clubman' UNION ALL
    SELECT 43,N'Cooper' UNION ALL
    SELECT 43,N'Countryman' UNION ALL
    SELECT 43,N'John Cooper Works' UNION ALL
    SELECT 43,N'One' UNION ALL
    SELECT 44,N'3000GT' UNION ALL
    SELECT 44,N'ASX' UNION ALL
    SELECT 44,N'Carisma' UNION ALL
    SELECT 44,N'Colt' UNION ALL
    SELECT 44,N'Delica' UNION ALL
    SELECT 44,N'Diamante' UNION ALL
    SELECT 44,N'Eclipse' UNION ALL
    SELECT 44,N'Endeavor' UNION ALL
    SELECT 44,N'Galant' UNION ALL
    SELECT 44,N'Grandis' UNION ALL
    SELECT 44,N'i-MiEV' UNION ALL
    SELECT 44,N'L200' UNION ALL
    SELECT 44,N'L300' UNION ALL
    SELECT 44,N'L400' UNION ALL
    SELECT 44,N'Lancer' UNION ALL
    SELECT 44,N'Lancer Evolution' UNION ALL
    SELECT 44,N'Mirage' UNION ALL
    SELECT 44,N'Montero' UNION ALL
    SELECT 44,N'Outlander' UNION ALL
    SELECT 44,N'Pajero' UNION ALL
    SELECT 44,N'Pajero Sport' UNION ALL
    SELECT 44,N'Raider' UNION ALL
    SELECT 44,N'RVR' UNION ALL
    SELECT 44,N'Sigma' UNION ALL
    SELECT 44,N'Space Gear' UNION ALL
    SELECT 44,N'Space Runner' UNION ALL
    SELECT 44,N'Space Star' UNION ALL
    SELECT 44,N'Space Wagon' UNION ALL
    SELECT 45,N'100NX' UNION ALL
    SELECT 45,N'200SX' UNION ALL
    SELECT 45,N'240SX' UNION ALL
    SELECT 45,N'300ZX' UNION ALL
    SELECT 45,N'350Z' UNION ALL
    SELECT 45,N'Almera' UNION ALL
    SELECT 45,N'Almera Tino' UNION ALL
    SELECT 45,N'Altima' UNION ALL
    SELECT 45,N'Armada' UNION ALL
    SELECT 45,N'Bluebird' UNION ALL
    SELECT 45,N'Cabstar' UNION ALL
    SELECT 45,N'Cedric' UNION ALL
    SELECT 45,N'Cefiro' UNION ALL
    SELECT 45,N'Cherry' UNION ALL
    SELECT 45,N'Cube' UNION ALL
    SELECT 45,N'Frontier' UNION ALL
    SELECT 45,N'GT-R' UNION ALL
    SELECT 45,N'Interstar' UNION ALL
    SELECT 45,N'Juke' UNION ALL
    SELECT 45,N'L50' UNION ALL
    SELECT 45,N'Laurel' UNION ALL
    SELECT 45,N'Leaf' UNION ALL
    SELECT 45,N'Liberta Villa' UNION ALL
    SELECT 45,N'Maxima' UNION ALL
    SELECT 45,N'Micra' UNION ALL
    SELECT 45,N'Murano' UNION ALL
    SELECT 45,N'Navara' UNION ALL
    SELECT 45,N'Note' UNION ALL
    SELECT 45,N'NP300 PICK UP' UNION ALL
    SELECT 45,N'NV200' UNION ALL
    SELECT 45,N'Pathfinder' UNION ALL
    SELECT 45,N'Patrol' UNION ALL
    SELECT 45,N'Pixo' UNION ALL
    SELECT 45,N'Prairie' UNION ALL
    SELECT 45,N'Primastar' UNION ALL
    SELECT 45,N'Primera' UNION ALL
    SELECT 45,N'Qashqai' UNION ALL
    SELECT 45,N'Qashqai+2' UNION ALL
    SELECT 45,N'Quest' UNION ALL
    SELECT 45,N'Rogue' UNION ALL
    SELECT 45,N'Sentra' UNION ALL
    SELECT 45,N'Serena' UNION ALL
    SELECT 45,N'Silvia' UNION ALL
    SELECT 45,N'Skyline' UNION ALL
    SELECT 45,N'Skyline GT-R' UNION ALL
    SELECT 45,N'Stanza' UNION ALL
    SELECT 45,N'Sunny' UNION ALL
    SELECT 45,N'Teana' UNION ALL
    SELECT 45,N'Terrano' UNION ALL
    SELECT 45,N'Tiida' UNION ALL
    SELECT 45,N'Tino' UNION ALL
    SELECT 45,N'Titan' UNION ALL
    SELECT 45,N'Trade' UNION ALL
    SELECT 45,N'Urvan' UNION ALL
    SELECT 45,N'Vanette' UNION ALL
    SELECT 45,N'Versa' UNION ALL
    SELECT 45,N'X-Trail' UNION ALL
    SELECT 45,N'Xterra' UNION ALL
    SELECT 46,N'Aurora' UNION ALL
    SELECT 46,N'Bravada' UNION ALL
    SELECT 46,N'Custom Cruiser' UNION ALL
    SELECT 46,N'Cutlass' UNION ALL
    SELECT 46,N'Delta 88' UNION ALL
    SELECT 46,N'Firenza' UNION ALL
    SELECT 46,N'Silhouette' UNION ALL
    SELECT 46,N'Supreme' UNION ALL
    SELECT 46,N'Toronado' UNION ALL
    SELECT 47,N'Adam' UNION ALL
    SELECT 47,N'Agila' UNION ALL
    SELECT 47,N'Ampera' UNION ALL
    SELECT 47,N'Antara' UNION ALL
    SELECT 47,N'Arena' UNION ALL
    SELECT 47,N'Ascona' UNION ALL
    SELECT 47,N'Astra' UNION ALL
    SELECT 47,N'Calibra' UNION ALL
    SELECT 47,N'Campo' UNION ALL
    SELECT 47,N'Cascada' UNION ALL
    SELECT 47,N'Cavalier' UNION ALL
    SELECT 47,N'Combo' UNION ALL
    SELECT 47,N'Commodore' UNION ALL
    SELECT 47,N'Corsa' UNION ALL
    SELECT 47,N'Diplomat' UNION ALL
    SELECT 47,N'Frontera' UNION ALL
    SELECT 47,N'GT' UNION ALL
    SELECT 47,N'Insignia' UNION ALL
    SELECT 47,N'Kadett' UNION ALL
    SELECT 47,N'Kapitan' UNION ALL
    SELECT 47,N'Manta' UNION ALL
    SELECT 47,N'Meriva' UNION ALL
    SELECT 47,N'Mokka' UNION ALL
    SELECT 47,N'Monterey' UNION ALL
    SELECT 47,N'Monza' UNION ALL
    SELECT 47,N'Movano' UNION ALL
    SELECT 47,N'Nova' UNION ALL
    SELECT 47,N'Olympia' UNION ALL
    SELECT 47,N'Omega' UNION ALL
    SELECT 47,N'Pick Up' UNION ALL
    SELECT 47,N'Rekord' UNION ALL
    SELECT 47,N'Senator' UNION ALL
    SELECT 47,N'Signum' UNION ALL
    SELECT 47,N'Sintra' UNION ALL
    SELECT 47,N'Speedster' UNION ALL
    SELECT 47,N'Tigra' UNION ALL
    SELECT 47,N'Vectra' UNION ALL
    SELECT 47,N'Vivaro' UNION ALL
    SELECT 47,N'Zafira' UNION ALL
    SELECT 48,N'1007' UNION ALL
    SELECT 48,N'104' UNION ALL
    SELECT 48,N'106' UNION ALL
    SELECT 48,N'107' UNION ALL
    SELECT 48,N'204' UNION ALL
    SELECT 48,N'205' UNION ALL
    SELECT 48,N'206' UNION ALL
    SELECT 48,N'207' UNION ALL
    SELECT 48,N'208' UNION ALL
    SELECT 48,N'3008' UNION ALL
    SELECT 48,N'301' UNION ALL
    SELECT 48,N'304' UNION ALL
    SELECT 48,N'305' UNION ALL
    SELECT 48,N'306' UNION ALL
    SELECT 48,N'307' UNION ALL
    SELECT 48,N'308' UNION ALL
    SELECT 48,N'309' UNION ALL
    SELECT 48,N'4007' UNION ALL
    SELECT 48,N'4008' UNION ALL
    SELECT 48,N'404' UNION ALL
    SELECT 48,N'405' UNION ALL
    SELECT 48,N'406' UNION ALL
    SELECT 48,N'407' UNION ALL
    SELECT 48,N'408' UNION ALL
    SELECT 48,N'5008' UNION ALL
    SELECT 48,N'504' UNION ALL
    SELECT 48,N'505' UNION ALL
    SELECT 48,N'508' UNION ALL
    SELECT 48,N'604' UNION ALL
    SELECT 48,N'605' UNION ALL
    SELECT 48,N'607' UNION ALL
    SELECT 48,N'805' UNION ALL
    SELECT 48,N'806' UNION ALL
    SELECT 48,N'807' UNION ALL
    SELECT 48,N'Bipper' UNION ALL
    SELECT 48,N'Bipper Tepee' UNION ALL
    SELECT 48,N'Boxer' UNION ALL
    SELECT 48,N'Expert' UNION ALL
    SELECT 48,N'Expert Tepee' UNION ALL
    SELECT 48,N'iOn' UNION ALL
    SELECT 48,N'J5' UNION ALL
    SELECT 48,N'J9' UNION ALL
    SELECT 48,N'Pars' UNION ALL
    SELECT 48,N'Partner' UNION ALL
    SELECT 48,N'Partner Tepee' UNION ALL
    SELECT 48,N'RCZ' UNION ALL
    SELECT 48,N'TePee' UNION ALL
    SELECT 49,N'6000' UNION ALL
    SELECT 49,N'Aztek' UNION ALL
    SELECT 49,N'Bonneville' UNION ALL
    SELECT 49,N'Fiero' UNION ALL
    SELECT 49,N'Firebird' UNION ALL
    SELECT 49,N'G3' UNION ALL
    SELECT 49,N'G5' UNION ALL
    SELECT 49,N'G6' UNION ALL
    SELECT 49,N'G8' UNION ALL
    SELECT 49,N'Grand Am' UNION ALL
    SELECT 49,N'Grand Prix' UNION ALL
    SELECT 49,N'GTO' UNION ALL
    SELECT 49,N'LeMans' UNION ALL
    SELECT 49,N'Montana' UNION ALL
    SELECT 49,N'Solstice' UNION ALL
    SELECT 49,N'Sunbird' UNION ALL
    SELECT 49,N'Sunfire' UNION ALL
    SELECT 49,N'T1000' UNION ALL
    SELECT 49,N'Torrent' UNION ALL
    SELECT 49,N'Trans Sport' UNION ALL
    SELECT 49,N'Vibe' UNION ALL
    SELECT 5,N'840' UNION ALL
    SELECT 5,N'850' UNION ALL
    SELECT 5,N'Gran Coupe' UNION ALL
    SELECT 5,N'Gran Turismo' UNION ALL
    SELECT 50,N'911' UNION ALL
    SELECT 50,N'912' UNION ALL
    SELECT 50,N'914' UNION ALL
    SELECT 50,N'924' UNION ALL
    SELECT 50,N'928' UNION ALL
    SELECT 50,N'944' UNION ALL
    SELECT 50,N'968' UNION ALL
    SELECT 50,N'996' UNION ALL
    SELECT 50,N'Boxster' UNION ALL
    SELECT 50,N'Carrera GT' UNION ALL
    SELECT 50,N'Cayenne' UNION ALL
    SELECT 50,N'Cayman' UNION ALL
    SELECT 50,N'Macan' UNION ALL
    SELECT 50,N'Panamera' UNION ALL
    SELECT 51,N'300-Series' UNION ALL
    SELECT 51,N'400-Series' UNION ALL
    SELECT 51,N'Perdana' UNION ALL
    SELECT 51,N'Persona' UNION ALL
    SELECT 51,N'Salon Airoback' UNION ALL
    SELECT 51,N'Satria' UNION ALL
    SELECT 51,N'Waja' UNION ALL
    SELECT 51,N'Wira' UNION ALL
    SELECT 52,N'11' UNION ALL
    SELECT 52,N'14' UNION ALL
    SELECT 52,N'17' UNION ALL
    SELECT 52,N'18' UNION ALL
    SELECT 52,N'19' UNION ALL
    SELECT 52,N'20' UNION ALL
    SELECT 52,N'21' UNION ALL
    SELECT 52,N'25' UNION ALL
    SELECT 52,N'30' UNION ALL
    SELECT 52,N'4' UNION ALL
    SELECT 52,N'5' UNION ALL
    SELECT 52,N'6' UNION ALL
    SELECT 52,N'9' UNION ALL
    SELECT 52,N'Alpine' UNION ALL
    SELECT 52,N'Avantime' UNION ALL
    SELECT 52,N'Clio' UNION ALL
    SELECT 52,N'Coupe' UNION ALL
    SELECT 52,N'Dokker' UNION ALL
    SELECT 52,N'Duster' UNION ALL
    SELECT 52,N'Espace' UNION ALL
    SELECT 52,N'Express' UNION ALL
    SELECT 52,N'Fluence' UNION ALL
    SELECT 52,N'Fuego' UNION ALL
    SELECT 52,N'Grand Espace' UNION ALL
    SELECT 52,N'Grand Modus' UNION ALL
    SELECT 52,N'Grand Scenic' UNION ALL
    SELECT 52,N'Kangoo' UNION ALL
    SELECT 52,N'Koleos' UNION ALL
    SELECT 52,N'Laguna' UNION ALL
    SELECT 52,N'Latitude' UNION ALL
    SELECT 52,N'Lodgy' UNION ALL
    SELECT 52,N'Logan' UNION ALL
    SELECT 52,N'Manager' UNION ALL
    SELECT 52,N'Mascott' UNION ALL
    SELECT 52,N'Master' UNION ALL
    SELECT 52,N'Maxity' UNION ALL
    SELECT 52,N'Megane' UNION ALL
    SELECT 52,N'Megane Scenic' UNION ALL
    SELECT 52,N'Messenger' UNION ALL
    SELECT 52,N'Modus' UNION ALL
    SELECT 52,N'P1400' UNION ALL
    SELECT 52,N'Rapid' UNION ALL
    SELECT 52,N'Safrane' UNION ALL
    SELECT 52,N'Sandero' UNION ALL
    SELECT 52,N'Scenic' UNION ALL
    SELECT 52,N'Spider' UNION ALL
    SELECT 52,N'Symbol' UNION ALL
    SELECT 52,N'Thalia' UNION ALL
    SELECT 52,N'Trafic' UNION ALL
    SELECT 52,N'Twingo' UNION ALL
    SELECT 52,N'Twizy' UNION ALL
    SELECT 52,N'Vel Satis' UNION ALL
    SELECT 52,N'Wind' UNION ALL
    SELECT 53,N'100-Series' UNION ALL
    SELECT 53,N'111' UNION ALL
    SELECT 53,N'200-Series' UNION ALL
    SELECT 53,N'25' UNION ALL
    SELECT 53,N'3500' UNION ALL
    SELECT 53,N'400-Series' UNION ALL
    SELECT 53,N'45' UNION ALL
    SELECT 53,N'600-Series' UNION ALL
    SELECT 53,N'75' UNION ALL
    SELECT 53,N'800-Series' UNION ALL
    SELECT 53,N'Austin' UNION ALL
    SELECT 53,N'Maestro' UNION ALL
    SELECT 53,N'Metro' UNION ALL
    SELECT 53,N'MGF' UNION ALL
    SELECT 53,N'Mini' UNION ALL
    SELECT 53,N'Montego' UNION ALL
    SELECT 53,N'Ostin' UNION ALL
    SELECT 53,N'Vitesse' UNION ALL
    SELECT 54,N'3-Sep' UNION ALL
    SELECT 54,N'5-Sep' UNION ALL
    SELECT 54,N'9 - 7X' UNION ALL
    SELECT 54,N'9-2X' UNION ALL
    SELECT 54,N'900' UNION ALL
    SELECT 54,N'9000' UNION ALL
    SELECT 54,N'99' UNION ALL
    SELECT 55,N'L' UNION ALL
    SELECT 55,N'LS' UNION ALL
    SELECT 55,N'LW' UNION ALL
    SELECT 55,N'Outlook' UNION ALL
    SELECT 55,N'SC' UNION ALL
    SELECT 55,N'Sky' UNION ALL
    SELECT 55,N'SL' UNION ALL
    SELECT 55,N'SW' UNION ALL
    SELECT 55,N'VUE' UNION ALL
    SELECT 56,N'Alhambra' UNION ALL
    SELECT 56,N'Altea' UNION ALL
    SELECT 56,N'Arosa' UNION ALL
    SELECT 56,N'Cordoba' UNION ALL
    SELECT 56,N'Exeo' UNION ALL
    SELECT 56,N'Ibiza' UNION ALL
    SELECT 56,N'Inca' UNION ALL
    SELECT 56,N'Leon' UNION ALL
    SELECT 56,N'Malaga' UNION ALL
    SELECT 56,N'Marbella' UNION ALL
    SELECT 56,N'Terra' UNION ALL
    SELECT 56,N'Toledo' UNION ALL
    SELECT 57,N'105' UNION ALL
    SELECT 57,N'120' UNION ALL
    SELECT 57,N'1203' UNION ALL
    SELECT 57,N'130' UNION ALL
    SELECT 57,N'Citygo' UNION ALL
    SELECT 57,N'Fabia' UNION ALL
    SELECT 57,N'Favorit' UNION ALL
    SELECT 57,N'Felicia' UNION ALL
    SELECT 57,N'Forman' UNION ALL
    SELECT 57,N'Octavia' UNION ALL
    SELECT 57,N'Praktik' UNION ALL
    SELECT 57,N'Rapid' UNION ALL
    SELECT 57,N'Roomster' UNION ALL
    SELECT 57,N'Superb' UNION ALL
    SELECT 57,N'Yeti' UNION ALL
    SELECT 58,N'Actyon' UNION ALL
    SELECT 58,N'Chairman' UNION ALL
    SELECT 58,N'Family' UNION ALL
    SELECT 58,N'Istana' UNION ALL
    SELECT 58,N'Kallista' UNION ALL
    SELECT 58,N'Korando' UNION ALL
    SELECT 58,N'Kyron' UNION ALL
    SELECT 58,N'Musso' UNION ALL
    SELECT 58,N'Rexton' UNION ALL
    SELECT 58,N'Rodius' UNION ALL
    SELECT 59,N'Baja' UNION ALL
    SELECT 59,N'BRZ' UNION ALL
    SELECT 59,N'Forester' UNION ALL
    SELECT 59,N'Impreza' UNION ALL
    SELECT 59,N'Justy' UNION ALL
    SELECT 59,N'Legacy' UNION ALL
    SELECT 59,N'Leone' UNION ALL
    SELECT 59,N'Libero' UNION ALL
    SELECT 59,N'Outback' UNION ALL
    SELECT 59,N'SVX' UNION ALL
    SELECT 59,N'Trezia' UNION ALL
    SELECT 59,N'Tribeca' UNION ALL
    SELECT 59,N'Vivio' UNION ALL
    SELECT 59,N'XV' UNION ALL
    SELECT 6,N'BC3' UNION ALL
    SELECT 6,N'BS2' UNION ALL
    SELECT 6,N'BS4' UNION ALL
    SELECT 6,N'BS6' UNION ALL
    SELECT 6,N'H530' UNION ALL
    SELECT 6,N'V5' UNION ALL
    SELECT 60,N'Aerio' UNION ALL
    SELECT 60,N'Alto' UNION ALL
    SELECT 60,N'Baleno' UNION ALL
    SELECT 60,N'Carry' UNION ALL
    SELECT 60,N'Equator' UNION ALL
    SELECT 60,N'Forenza' UNION ALL
    SELECT 60,N'Grand Vitara' UNION ALL
    SELECT 60,N'Ignis' UNION ALL
    SELECT 60,N'Jimny' UNION ALL
    SELECT 60,N'Kizashi' UNION ALL
    SELECT 60,N'Liana' UNION ALL
    SELECT 60,N'Reno' UNION ALL
    SELECT 60,N'Samurai' UNION ALL
    SELECT 60,N'Splash' UNION ALL
    SELECT 60,N'Super Carry' UNION ALL
    SELECT 60,N'Swift' UNION ALL
    SELECT 60,N'SX4' UNION ALL
    SELECT 60,N'Verona' UNION ALL
    SELECT 60,N'Vitara' UNION ALL
    SELECT 60,N'Wagon R' UNION ALL
    SELECT 60,N'XL7' UNION ALL
    SELECT 61,N'4Runner' UNION ALL
    SELECT 61,N'Alphard' UNION ALL
    SELECT 61,N'Altezza' UNION ALL
    SELECT 61,N'Auris' UNION ALL
    SELECT 61,N'Avalon' UNION ALL
    SELECT 61,N'Avensis' UNION ALL
    SELECT 61,N'Aygo' UNION ALL
    SELECT 61,N'BB' UNION ALL
    SELECT 61,N'Camry' UNION ALL
    SELECT 61,N'Carina E' UNION ALL
    SELECT 61,N'Carina II' UNION ALL
    SELECT 61,N'Celica' UNION ALL
    SELECT 61,N'Chaser' UNION ALL
    SELECT 61,N'Corolla' UNION ALL
    SELECT 61,N'Corolla Verso' UNION ALL
    SELECT 61,N'Corona' UNION ALL
    SELECT 61,N'Cressida' UNION ALL
    SELECT 61,N'Cresta' UNION ALL
    SELECT 61,N'Crown' UNION ALL
    SELECT 61,N'Echo' UNION ALL
    SELECT 61,N'FJ Cruiser' UNION ALL
    SELECT 61,N'Fortuner' UNION ALL
    SELECT 61,N'GT 86' UNION ALL
    SELECT 61,N'HiAce' UNION ALL
    SELECT 61,N'Highlander' UNION ALL
    SELECT 61,N'Hilux' UNION ALL
    SELECT 61,N'IQ' UNION ALL
    SELECT 61,N'Land Cruiser' UNION ALL
    SELECT 61,N'LiteAce' UNION ALL
    SELECT 61,N'Mark' UNION ALL
    SELECT 61,N'Matrix' UNION ALL
    SELECT 61,N'Model F' UNION ALL
    SELECT 61,N'MR2' UNION ALL
    SELECT 61,N'Paseo' UNION ALL
    SELECT 61,N'Picnic' UNION ALL
    SELECT 61,N'Previa' UNION ALL
    SELECT 61,N'Prius' UNION ALL
    SELECT 61,N'RAV4' UNION ALL
    SELECT 61,N'Sequoia' UNION ALL
    SELECT 61,N'Sienna' UNION ALL
    SELECT 61,N'Soarer' UNION ALL
    SELECT 61,N'Solara' UNION ALL
    SELECT 61,N'Starlet' UNION ALL
    SELECT 61,N'Supra' UNION ALL
    SELECT 61,N'Tacoma' UNION ALL
    SELECT 61,N'Tercel' UNION ALL
    SELECT 61,N'Tundra' UNION ALL
    SELECT 61,N'Urban Cruiser' UNION ALL
    SELECT 61,N'Venza' UNION ALL
    SELECT 61,N'Verso' UNION ALL
    SELECT 61,N'Vista' UNION ALL
    SELECT 61,N'Yaris' UNION ALL
    SELECT 62,N'181' UNION ALL
    SELECT 62,N'Amarok' UNION ALL
    SELECT 62,N'Beetle' UNION ALL
    SELECT 62,N'Bora' UNION ALL
    SELECT 62,N'Buggy' UNION ALL
    SELECT 62,N'Caddy' UNION ALL
    SELECT 62,N'Corrado' UNION ALL
    SELECT 62,N'Crafter' UNION ALL
    SELECT 62,N'Derby' UNION ALL
    SELECT 62,N'Eos' UNION ALL
    SELECT 62,N'Fox' UNION ALL
    SELECT 62,N'Gol' UNION ALL
    SELECT 62,N'Golf' UNION ALL
    SELECT 62,N'Golf Plus' UNION ALL
    SELECT 62,N'Iltis' UNION ALL
    SELECT 62,N'Jetta' UNION ALL
    SELECT 62,N'Kafer' UNION ALL
    SELECT 62,N'Karmann Ghia' UNION ALL
    SELECT 62,N'LT' UNION ALL
    SELECT 62,N'Lupo' UNION ALL
    SELECT 62,N'New Beetle' UNION ALL
    SELECT 62,N'Passat' UNION ALL
    SELECT 62,N'Passat CC' UNION ALL
    SELECT 62,N'Phaeton' UNION ALL
    SELECT 62,N'Pointer' UNION ALL
    SELECT 62,N'Polo' UNION ALL
    SELECT 62,N'Polo Sedan' UNION ALL
    SELECT 62,N'Routan' UNION ALL
    SELECT 62,N'Santana' UNION ALL
    SELECT 62,N'Scirocco' UNION ALL
    SELECT 62,N'Sharan' UNION ALL
    SELECT 62,N'T1' UNION ALL
    SELECT 62,N'T2' UNION ALL
    SELECT 62,N'T3' UNION ALL
    SELECT 62,N'T3 Caravelle' UNION ALL
    SELECT 62,N'T3 Multivan' UNION ALL
    SELECT 62,N'T4' UNION ALL
    SELECT 62,N'T4 Caravelle' UNION ALL
    SELECT 62,N'T4 Multivan' UNION ALL
    SELECT 62,N'T5' UNION ALL
    SELECT 62,N'T5 Caravelle' UNION ALL
    SELECT 62,N'T5 Multivan' UNION ALL
    SELECT 62,N'T5 Shuttle' UNION ALL
    SELECT 62,N'Taro' UNION ALL
    SELECT 62,N'Tiguan' UNION ALL
    SELECT 62,N'Touareg' UNION ALL
    SELECT 62,N'Touran' UNION ALL
    SELECT 62,N'Up' UNION ALL
    SELECT 62,N'Vento' UNION ALL
    SELECT 63,N'240' UNION ALL
    SELECT 63,N'242' UNION ALL
    SELECT 63,N'244' UNION ALL
    SELECT 63,N'245' UNION ALL
    SELECT 63,N'262' UNION ALL
    SELECT 63,N'264' UNION ALL
    SELECT 63,N'340' UNION ALL
    SELECT 63,N'343' UNION ALL
    SELECT 63,N'360' UNION ALL
    SELECT 63,N'440' UNION ALL
    SELECT 63,N'460' UNION ALL
    SELECT 63,N'480' UNION ALL
    SELECT 63,N'740' UNION ALL
    SELECT 63,N'744' UNION ALL
    SELECT 63,N'745' UNION ALL
    SELECT 63,N'760' UNION ALL
    SELECT 63,N'780' UNION ALL
    SELECT 63,N'850' UNION ALL
    SELECT 63,N'855' UNION ALL
    SELECT 63,N'940' UNION ALL
    SELECT 63,N'944' UNION ALL
    SELECT 63,N'945' UNION ALL
    SELECT 63,N'960' UNION ALL
    SELECT 63,N'965' UNION ALL
    SELECT 63,N'Amazon' UNION ALL
    SELECT 63,N'C30' UNION ALL
    SELECT 63,N'C70' UNION ALL
    SELECT 63,N'Polar' UNION ALL
    SELECT 63,N'S40' UNION ALL
    SELECT 63,N'S60' UNION ALL
    SELECT 63,N'S70' UNION ALL
    SELECT 63,N'S80' UNION ALL
    SELECT 63,N'S90' UNION ALL
    SELECT 63,N'V40' UNION ALL
    SELECT 63,N'V50' UNION ALL
    SELECT 63,N'V60' UNION ALL
    SELECT 63,N'V70' UNION ALL
    SELECT 63,N'V90' UNION ALL
    SELECT 63,N'XC60' UNION ALL
    SELECT 63,N'XC70' UNION ALL
    SELECT 63,N'XC90' UNION ALL
    SELECT 65,N'1111' UNION ALL
    SELECT 65,N'1119' UNION ALL
    SELECT 65,N'2101' UNION ALL
    SELECT 65,N'2102' UNION ALL
    SELECT 65,N'2103' UNION ALL
    SELECT 65,N'2104' UNION ALL
    SELECT 65,N'2105' UNION ALL
    SELECT 65,N'2106' UNION ALL
    SELECT 65,N'2107' UNION ALL
    SELECT 65,N'2108' UNION ALL
    SELECT 65,N'2109' UNION ALL
    SELECT 65,N'21099' UNION ALL
    SELECT 65,N'2110' UNION ALL
    SELECT 65,N'2111' UNION ALL
    SELECT 65,N'2112' UNION ALL
    SELECT 65,N'2113' UNION ALL
    SELECT 65,N'2114' UNION ALL
    SELECT 65,N'2115' UNION ALL
    SELECT 65,N'2120' UNION ALL
    SELECT 65,N'2121' UNION ALL
    SELECT 65,N'21213' UNION ALL
    SELECT 65,N'21215' UNION ALL
    SELECT 65,N'21218' UNION ALL
    SELECT 65,N'2123' UNION ALL
    SELECT 65,N'2129' UNION ALL
    SELECT 65,N'2130' UNION ALL
    SELECT 65,N'2131' UNION ALL
    SELECT 65,N'2310' UNION ALL
    SELECT 65,N'2328' UNION ALL
    SELECT 65,N'2329' UNION ALL
    SELECT 65,N'Granta' UNION ALL
    SELECT 65,N'Kalina' UNION ALL
    SELECT 65,N'Largus' UNION ALL
    SELECT 65,N'Priora' UNION ALL
    SELECT 65,N'ВИС' UNION ALL
    SELECT 65,N'Лаура' UNION ALL
    SELECT 66,N'12' UNION ALL
    SELECT 66,N'14' UNION ALL
    SELECT 66,N'21' UNION ALL
    SELECT 66,N'22' UNION ALL
    SELECT 66,N'23' UNION ALL
    SELECT 66,N'24' UNION ALL
    SELECT 66,N'2401' UNION ALL
    SELECT 66,N'2402' UNION ALL
    SELECT 66,N'2410' UNION ALL
    SELECT 66,N'2705' UNION ALL
    SELECT 66,N'2752' UNION ALL
    SELECT 66,N'2757' UNION ALL
    SELECT 66,N'3102' UNION ALL
    SELECT 66,N'310210' UNION ALL
    SELECT 66,N'31022' UNION ALL
    SELECT 66,N'310221' UNION ALL
    SELECT 66,N'31029' UNION ALL
    SELECT 66,N'3110' UNION ALL
    SELECT 66,N'31105' UNION ALL
    SELECT 66,N'3111' UNION ALL
    SELECT 66,N'322132' UNION ALL
    SELECT 66,N'322133' UNION ALL
    SELECT 66,N'3285' UNION ALL
    SELECT 66,N'3302' UNION ALL
    SELECT 66,N'67' UNION ALL
    SELECT 66,N'69' UNION ALL
    SELECT 66,N'Siber' UNION ALL
    SELECT 66,N'А21' UNION ALL
    SELECT 66,N'А22' UNION ALL
    SELECT 66,N'Луидор' UNION ALL
    SELECT 66,N'М20' UNION ALL
    SELECT 66,N'Семар' UNION ALL
    SELECT 67,N'1103' UNION ALL
    SELECT 67,N'68' UNION ALL
    SELECT 67,N'965' UNION ALL
    SELECT 67,N'966' UNION ALL
    SELECT 67,N'968а' UNION ALL
    SELECT 67,N'968м' UNION ALL
    SELECT 67,N'Chance' UNION ALL
    SELECT 67,N'Forza' UNION ALL
    SELECT 67,N'Sens' UNION ALL
    SELECT 67,N'Vida' UNION ALL
    SELECT 67,N'Дана' UNION ALL
    SELECT 67,N'МД' UNION ALL
    SELECT 67,N'Таврия' UNION ALL
    SELECT 68,N'2125' UNION ALL
    SELECT 68,N'2136 Kombi' UNION ALL
    SELECT 68,N'2137 Kombi' UNION ALL
    SELECT 68,N'2138' UNION ALL
    SELECT 68,N'2140' UNION ALL
    SELECT 68,N'2141' UNION ALL
    SELECT 68,N'2149' UNION ALL
    SELECT 68,N'400' UNION ALL
    SELECT 68,N'401' UNION ALL
    SELECT 68,N'402' UNION ALL
    SELECT 68,N'403' UNION ALL
    SELECT 68,N'406' UNION ALL
    SELECT 68,N'407' UNION ALL
    SELECT 68,N'408' UNION ALL
    SELECT 68,N'412' UNION ALL
    SELECT 68,N'423 Kombi' UNION ALL
    SELECT 68,N'426' UNION ALL
    SELECT 68,N'427' UNION ALL
    SELECT 68,N'434' UNION ALL
    SELECT 68,N'Князь Владимир' UNION ALL
    SELECT 68,N'Святогор' UNION ALL
    SELECT 68,N'Юрий Долгорукий' UNION ALL
    SELECT 7,N'Apollo' UNION ALL
    SELECT 7,N'Century' UNION ALL
    SELECT 7,N'Electra Wagon' UNION ALL
    SELECT 7,N'Enclave' UNION ALL
    SELECT 7,N'Encore' UNION ALL
    SELECT 7,N'GL8' UNION ALL
    SELECT 7,N'LaCrosse' UNION ALL
    SELECT 7,N'Le Sabre' UNION ALL
    SELECT 7,N'Lucerne' UNION ALL
    SELECT 7,N'Park Avenue' UNION ALL
    SELECT 7,N'Reatta' UNION ALL
    SELECT 7,N'Regal' UNION ALL
    SELECT 7,N'Rendez Vous' UNION ALL
    SELECT 7,N'Rivera' UNION ALL
    SELECT 7,N'Roadmaster' UNION ALL
    SELECT 7,N'Skylark' UNION ALL
    SELECT 70,N'2206' UNION ALL
    SELECT 70,N'3151' UNION ALL
    SELECT 70,N'31512' UNION ALL
    SELECT 70,N'31514' UNION ALL
    SELECT 70,N'3153' UNION ALL
    SELECT 70,N'3160' UNION ALL
    SELECT 70,N'3303' UNION ALL
    SELECT 70,N'3741' UNION ALL
    SELECT 70,N'39099' UNION ALL
    SELECT 70,N'3962' UNION ALL
    SELECT 70,N'451' UNION ALL
    SELECT 70,N'452' UNION ALL
    SELECT 70,N'469' UNION ALL
    SELECT 70,N'69A' UNION ALL
    SELECT 70,N'Hunter' UNION ALL
    SELECT 70,N'Patriot' UNION ALL
    SELECT 71,N'Daily' UNION ALL
    SELECT 72,N'1307' UNION ALL
    SELECT 72,N'1308' UNION ALL
    SELECT 72,N'1309' UNION ALL
    SELECT 73,N'2125' UNION ALL
    SELECT 73,N'2126' UNION ALL
    SELECT 73,N'2715' UNION ALL
    SELECT 73,N'2717' UNION ALL
    SELECT 74,N'967М' UNION ALL
    SELECT 74,N'969' UNION ALL
    SELECT 75,N'Breeze' UNION ALL
    SELECT 75,N'Grand Voyager' UNION ALL
    SELECT 75,N'Horizon' UNION ALL
    SELECT 75,N'Neon' UNION ALL
    SELECT 75,N'Reliant' UNION ALL
    SELECT 75,N'Sundance' UNION ALL
    SELECT 75,N'Voyager' UNION ALL
    SELECT 76,N'B1000' UNION ALL
    SELECT 77,N'Brio' UNION ALL
    SELECT 77,N'Lobo' UNION ALL
    SELECT 77,N'Minyi' UNION ALL
    SELECT 77,N'Princip' UNION ALL
    SELECT 77,N'Simbo' UNION ALL
    SELECT 78,N'3' UNION ALL
    SELECT 78,N'350' UNION ALL
    SELECT 78,N'5' UNION ALL
    SELECT 78,N'550' UNION ALL
    SELECT 78,N'6' UNION ALL
    SELECT 78,N'750' UNION ALL
    SELECT 78,N'950' UNION ALL
    SELECT 78,N'ZR' UNION ALL
    SELECT 78,N'ZS' UNION ALL
    SELECT 78,N'ZT' UNION ALL
    SELECT 79,N'Aventador' UNION ALL
    SELECT 79,N'Countach' UNION ALL
    SELECT 79,N'Diablo' UNION ALL
    SELECT 79,N'Gallardo' UNION ALL
    SELECT 79,N'Murcielago' UNION ALL
    SELECT 79,N'Reventon' UNION ALL
    SELECT 8,N'Allante' UNION ALL
    SELECT 8,N'ATS' UNION ALL
    SELECT 8,N'BLS' UNION ALL
    SELECT 8,N'Brogham' UNION ALL
    SELECT 8,N'Catera' UNION ALL
    SELECT 8,N'Cimarron' UNION ALL
    SELECT 8,N'CTS' UNION ALL
    SELECT 8,N'De Ville' UNION ALL
    SELECT 8,N'DTS' UNION ALL
    SELECT 8,N'Eldorado' UNION ALL
    SELECT 8,N'Escalade' UNION ALL
    SELECT 8,N'Evoq' UNION ALL
    SELECT 8,N'Flitwood' UNION ALL
    SELECT 8,N'GLS' UNION ALL
    SELECT 8,N'Seville' UNION ALL
    SELECT 8,N'SRX' UNION ALL
    SELECT 8,N'STS' UNION ALL
    SELECT 8,N'Superior' UNION ALL
    SELECT 8,N'Vizon' UNION ALL
    SELECT 8,N'XLR' UNION ALL
    SELECT 80,N'FR-S' UNION ALL
    SELECT 80,N'tC' UNION ALL
    SELECT 80,N'xA' UNION ALL
    SELECT 80,N'xB' UNION ALL
    SELECT 81,N'353' UNION ALL
    SELECT 81,N'Tourist' UNION ALL
    SELECT 87,N'6371' UNION ALL
    SELECT 87,N'Besturn B' UNION ALL
    SELECT 87,N'Jinn' UNION ALL
    SELECT 87,N'Vela' UNION ALL
    SELECT 87,N'Vita' UNION ALL
    SELECT 87,N'Vita Sedan' UNION ALL
    SELECT 87,N'Vizi V5' UNION ALL
    SELECT 87,N'Xiali N5' UNION ALL
    SELECT 88,N'A15' UNION ALL
    SELECT 88,N'A21' UNION ALL
    SELECT 88,N'A31' UNION ALL
    SELECT 88,N'A75' UNION ALL
    SELECT 88,N'D-Line' UNION ALL
    SELECT 88,N'Ikarus 553' UNION ALL
    SELECT 88,N'S430' UNION ALL
    SELECT 9,N'A1' UNION ALL
    SELECT 9,N'A13' UNION ALL
    SELECT 9,N'A5' UNION ALL
    SELECT 9,N'Amulet' UNION ALL
    SELECT 9,N'Arrizo' UNION ALL
    SELECT 9,N'Bonus' UNION ALL
    SELECT 9,N'Cowin' UNION ALL
    SELECT 9,N'Cross Eastar' UNION ALL
    SELECT 9,N'Indis' UNION ALL
    SELECT 9,N'Kimo' UNION ALL
    SELECT 9,N'M11' UNION ALL
    SELECT 9,N'Oriental Son' UNION ALL
    SELECT 9,N'QQ' UNION ALL
    SELECT 9,N'QQ6' UNION ALL
    SELECT 9,N'Tiggo' UNION ALL
    SELECT 9,N'V5' UNION ALL
    SELECT 9,N'Very' UNION ALL
    SELECT 91,N'200' UNION ALL
    SELECT 91,N'400' UNION ALL
    SELECT 91,N'46' UNION ALL
    SELECT 91,N'66' UNION ALL
    SELECT 92,N'2203' UNION ALL
    SELECT 93,N'Fenix' UNION ALL
    SELECT 94,N'DB9' UNION ALL
    SELECT 94,N'V12 Vantage' UNION ALL
    SELECT 94,N'V8 Vantage' UNION ALL
    SELECT 95,N'Horizon' UNION ALL
    SELECT 95,N'Solara' UNION ALL
    SELECT 96,N'1.1' UNION ALL
    SELECT 96,N'601' UNION ALL
    SELECT 96,N'P50' UNION ALL
    SELECT 96,N'P60' UNION ALL
    SELECT 96,N'P70' UNION ALL
    SELECT 97,N'Anibal' UNION ALL
    SELECT 98,N'Rocsta' UNION ALL
    SELECT 98,N'Towner' UNION ALL
    SELECT 99,N'320' UNION ALL
    SELECT 99,N'520' UNION ALL
    SELECT 99,N'620' UNION ALL
    SELECT 99,N'Breez' UNION ALL
    SELECT 99,N'Cebrium' UNION ALL
    SELECT 99,N'Celliya' UNION ALL
    SELECT 99,N'Smily' UNION ALL
    SELECT 99,N'Solano' UNION ALL
    SELECT 99,N'X60' UNION ALL
    SELECT 5,N'116' UNION ALL
    SELECT 5,N'118' UNION ALL
    SELECT 5,N'120' UNION ALL
    SELECT 5,N'123' UNION ALL
    SELECT 5,N'125' UNION ALL
    SELECT 5,N'128' UNION ALL
    SELECT 5,N'130' UNION ALL
    SELECT 5,N'135' UNION ALL
    SELECT 5,N'214' UNION ALL
    SELECT 5,N'216' UNION ALL
    SELECT 5,N'218' UNION ALL
    SELECT 5,N'220' UNION ALL
    SELECT 5,N'225' UNION ALL
    SELECT 5,N'315' UNION ALL
    SELECT 5,N'316' UNION ALL
    SELECT 5,N'318' UNION ALL
    SELECT 5,N'320' UNION ALL
    SELECT 5,N'322' UNION ALL
    SELECT 5,N'323' UNION ALL
    SELECT 5,N'324' UNION ALL
    SELECT 5,N'325' UNION ALL
    SELECT 5,N'328' UNION ALL
    SELECT 5,N'330' UNION ALL
    SELECT 5,N'335' UNION ALL
    SELECT 5,N'428' UNION ALL
    SELECT 5,N'435' UNION ALL
    SELECT 5,N'518' UNION ALL
    SELECT 5,N'520' UNION ALL
    SELECT 5,N'523' UNION ALL
    SELECT 5,N'524' UNION ALL
    SELECT 5,N'525' UNION ALL
    SELECT 5,N'528' UNION ALL
    SELECT 5,N'530' UNION ALL
    SELECT 5,N'535' UNION ALL
    SELECT 5,N'539' UNION ALL
    SELECT 5,N'540' UNION ALL
    SELECT 5,N'545' UNION ALL
    SELECT 5,N'550' UNION ALL
    SELECT 5,N'628' UNION ALL
    SELECT 5,N'630' UNION ALL
    SELECT 5,N'633' UNION ALL
    SELECT 5,N'635' UNION ALL
    SELECT 5,N'645' UNION ALL
    SELECT 5,N'650' UNION ALL
    SELECT 5,N'725' UNION ALL
    SELECT 5,N'728' UNION ALL
    SELECT 5,N'730' UNION ALL
    SELECT 5,N'732' UNION ALL
    SELECT 5,N'735' UNION ALL
    SELECT 5,N'740' UNION ALL
    SELECT 5,N'745' UNION ALL
    SELECT 5,N'750' UNION ALL
    SELECT 5,N'760' UNION ALL
    SELECT 5,N'M3' UNION ALL
    SELECT 5,N'M6' UNION ALL
    SELECT 5,N'М5' UNION ALL
    SELECT 5,N'X1' UNION ALL
    SELECT 5,N'X3' UNION ALL
    SELECT 5,N'X4' UNION ALL
    SELECT 5,N'X5' UNION ALL
    SELECT 5,N'X5 M' UNION ALL
    SELECT 5,N'X6' UNION ALL
    SELECT 5,N'X6 M' UNION ALL
    SELECT 5,N'Z3' UNION ALL
    SELECT 5,N'Z4' UNION ALL
    SELECT 5,N'Z8' UNION ALL
    SELECT 41,N'190' UNION ALL
    SELECT 41,N'C160' UNION ALL
    SELECT 41,N'C180' UNION ALL
    SELECT 41,N'C200' UNION ALL
    SELECT 41,N'C220' UNION ALL
    SELECT 41,N'C230' UNION ALL
    SELECT 41,N'C240' UNION ALL
    SELECT 41,N'C250' UNION ALL
    SELECT 41,N'C270' UNION ALL
    SELECT 41,N'C280' UNION ALL
    SELECT 41,N'C30 AMG' UNION ALL
    SELECT 41,N'C300' UNION ALL
    SELECT 41,N'C32 AMG' UNION ALL
    SELECT 41,N'C320' UNION ALL
    SELECT 41,N'C350' UNION ALL
    SELECT 41,N'C36AMG' UNION ALL
    SELECT 41,N'C43AMG' UNION ALL
    SELECT 41,N'C55AMG' UNION ALL
    SELECT 41,N'C63AMG' UNION ALL
    SELECT 41,N'A140' UNION ALL
    SELECT 41,N'A150' UNION ALL
    SELECT 41,N'A160' UNION ALL
    SELECT 41,N'A170' UNION ALL
    SELECT 41,N'A180' UNION ALL
    SELECT 41,N'A190' UNION ALL
    SELECT 41,N'A200' UNION ALL
    SELECT 41,N'A210' UNION ALL
    SELECT 41,N'A220' UNION ALL
    SELECT 41,N'A250' UNION ALL
    SELECT 41,N'A45 AMG' UNION ALL
    SELECT 41,N'B150' UNION ALL
    SELECT 41,N'B160' UNION ALL
    SELECT 41,N'B170' UNION ALL
    SELECT 41,N'B180' UNION ALL
    SELECT 41,N'B200' UNION ALL
    SELECT 41,N'B220' UNION ALL
    SELECT 41,N'B250' UNION ALL
    SELECT 41,N'CL160' UNION ALL
    SELECT 41,N'CL180' UNION ALL
    SELECT 41,N'CL200' UNION ALL
    SELECT 41,N'CL220' UNION ALL
    SELECT 41,N'CL230' UNION ALL
    SELECT 41,N'CL320' UNION ALL
    SELECT 41,N'CL420' UNION ALL
    SELECT 41,N'CL500' UNION ALL
    SELECT 41,N'CL55 AMG' UNION ALL
    SELECT 41,N'CL600' UNION ALL
    SELECT 41,N'CL63 AMG' UNION ALL
    SELECT 41,N'CL65 AMG' UNION ALL
    SELECT 41,N'CLA180' UNION ALL
    SELECT 41,N'CLA200' UNION ALL
    SELECT 41,N'CLA220' UNION ALL
    SELECT 41,N'CLA250' UNION ALL
    SELECT 41,N'CLA45 AMG' UNION ALL
    SELECT 41,N'CLC160' UNION ALL
    SELECT 41,N'CLC180' UNION ALL
    SELECT 41,N'CLC200' UNION ALL
    SELECT 41,N'CLC220' UNION ALL
    SELECT 41,N'CLC230' UNION ALL
    SELECT 41,N'CLC250' UNION ALL
    SELECT 41,N'CLC350' UNION ALL
    SELECT 41,N'CLK200' UNION ALL
    SELECT 41,N'CLK220' UNION ALL
    SELECT 41,N'CLK230' UNION ALL
    SELECT 41,N'CLK240' UNION ALL
    SELECT 41,N'CLK270' UNION ALL
    SELECT 41,N'CLK280' UNION ALL
    SELECT 41,N'CLK320' UNION ALL
    SELECT 41,N'CLK350' UNION ALL
    SELECT 41,N'CLK430' UNION ALL
    SELECT 41,N'CLK500' UNION ALL
    SELECT 41,N'CLK55 AMG' UNION ALL
    SELECT 41,N'CLK550' UNION ALL
    SELECT 41,N'CLK63 AMG' UNION ALL
    SELECT 41,N'CLS250' UNION ALL
    SELECT 41,N'CLS280' UNION ALL
    SELECT 41,N'CLS300' UNION ALL
    SELECT 41,N'CLS320' UNION ALL
    SELECT 41,N'CLS350' UNION ALL
    SELECT 41,N'CLS500' UNION ALL
    SELECT 41,N'CLS55 AMG' UNION ALL
    SELECT 41,N'CLS550' UNION ALL
    SELECT 41,N'CLS63 AMG' UNION ALL
    SELECT 41,N'E200' UNION ALL
    SELECT 41,N'E220' UNION ALL
    SELECT 41,N'E230' UNION ALL
    SELECT 41,N'E240' UNION ALL
    SELECT 41,N'E250' UNION ALL
    SELECT 41,N'E260' UNION ALL
    SELECT 41,N'E270' UNION ALL
    SELECT 41,N'E280' UNION ALL
    SELECT 41,N'E290' UNION ALL
    SELECT 41,N'E300' UNION ALL
    SELECT 41,N'E320' UNION ALL
    SELECT 41,N'E350' UNION ALL
    SELECT 41,N'E36 AMG' UNION ALL
    SELECT 41,N'E400' UNION ALL
    SELECT 41,N'E420' UNION ALL
    SELECT 41,N'E430' UNION ALL
    SELECT 41,N'E50 AMG' UNION ALL
    SELECT 41,N'E500' UNION ALL
    SELECT 41,N'E55 AMG' UNION ALL
    SELECT 41,N'E550' UNION ALL
    SELECT 41,N'E60 AMG' UNION ALL
    SELECT 41,N'E63 AMG' UNION ALL
    SELECT 41,N'G230' UNION ALL
    SELECT 41,N'G240' UNION ALL
    SELECT 41,N'G250' UNION ALL
    SELECT 41,N'G270' UNION ALL
    SELECT 41,N'G280' UNION ALL
    SELECT 41,N'G290' UNION ALL
    SELECT 41,N'G300' UNION ALL
    SELECT 41,N'G320' UNION ALL
    SELECT 41,N'G350' UNION ALL
    SELECT 41,N'G36 AMG' UNION ALL
    SELECT 41,N'G400' UNION ALL
    SELECT 41,N'G500' UNION ALL
    SELECT 41,N'G55 AMG' UNION ALL
    SELECT 41,N'G550' UNION ALL
    SELECT 41,N'G63' UNION ALL
    SELECT 41,N'GL320' UNION ALL
    SELECT 41,N'GL350' UNION ALL
    SELECT 41,N'GL420' UNION ALL
    SELECT 41,N'GL450' UNION ALL
    SELECT 41,N'GL500' UNION ALL
    SELECT 41,N'GL550' UNION ALL
    SELECT 41,N'GL63' UNION ALL
    SELECT 41,N'GLA200' UNION ALL
    SELECT 41,N'GLA220' UNION ALL
    SELECT 41,N'GLA250' UNION ALL
    SELECT 41,N'GLA45 AMG' UNION ALL
    SELECT 41,N'GLC300' UNION ALL
    SELECT 41,N'GLK200' UNION ALL
    SELECT 41,N'GLK220' UNION ALL
    SELECT 41,N'GLK250' UNION ALL
    SELECT 41,N'GLK280' UNION ALL
    SELECT 41,N'GLK300' UNION ALL
    SELECT 41,N'GLK320' UNION ALL
    SELECT 41,N'GLK350' UNION ALL
    SELECT 41,N'ML230' UNION ALL
    SELECT 41,N'ML250' UNION ALL
    SELECT 41,N'ML270' UNION ALL
    SELECT 41,N'ML280' UNION ALL
    SELECT 41,N'ML300' UNION ALL
    SELECT 41,N'ML320' UNION ALL
    SELECT 41,N'ML350' UNION ALL
    SELECT 41,N'ML400' UNION ALL
    SELECT 41,N'ML420' UNION ALL
    SELECT 41,N'ML430' UNION ALL
    SELECT 41,N'ML450' UNION ALL
    SELECT 41,N'ML500' UNION ALL
    SELECT 41,N'ML55 AMG' UNION ALL
    SELECT 41,N'ML550' UNION ALL
    SELECT 41,N'ML63 AMG' UNION ALL
    SELECT 41,N'R280' UNION ALL
    SELECT 41,N'R300' UNION ALL
    SELECT 41,N'R320' UNION ALL
    SELECT 41,N'R350' UNION ALL
    SELECT 41,N'R500' UNION ALL
    SELECT 41,N'R63 AMG' UNION ALL
    SELECT 41,N'S220' UNION ALL
    SELECT 41,N'S250' UNION ALL
    SELECT 41,N'S260' UNION ALL
    SELECT 41,N'S280' UNION ALL
    SELECT 41,N'S300' UNION ALL
    SELECT 41,N'S320' UNION ALL
    SELECT 41,N'S350' UNION ALL
    SELECT 41,N'S380' UNION ALL
    SELECT 41,N'S400' UNION ALL
    SELECT 41,N'S420' UNION ALL
    SELECT 41,N'S430' UNION ALL
    SELECT 41,N'S450' UNION ALL
    SELECT 41,N'S500' UNION ALL
    SELECT 41,N'S55 AMG' UNION ALL
    SELECT 41,N'S550' UNION ALL
    SELECT 41,N'S560' UNION ALL
    SELECT 41,N'S600' UNION ALL
    SELECT 41,N'S63 AMG' UNION ALL
    SELECT 41,N'S65 AMG' UNION ALL
    SELECT 41,N'SL280' UNION ALL
    SELECT 41,N'SL300' UNION ALL
    SELECT 41,N'SL320' UNION ALL
    SELECT 41,N'SL350' UNION ALL
    SELECT 41,N'SL380' UNION ALL
    SELECT 41,N'SL420' UNION ALL
    SELECT 41,N'SL450' UNION ALL
    SELECT 41,N'SL500' UNION ALL
    SELECT 41,N'SL55 AMG' UNION ALL
    SELECT 41,N'SL560' UNION ALL
    SELECT 41,N'SL60 AMG' UNION ALL
    SELECT 41,N'SL600' UNION ALL
    SELECT 41,N'SL63 AMG' UNION ALL
    SELECT 41,N'SL70 AMG' UNION ALL
    SELECT 41,N'SL73 AMG' UNION ALL
    SELECT 41,N'SL75 AMG' UNION ALL
    SELECT 41,N'SLK200' UNION ALL
    SELECT 41,N'SLK230' UNION ALL
    SELECT 41,N'SLK250' UNION ALL
    SELECT 41,N'SLK280' UNION ALL
    SELECT 41,N'SLK300' UNION ALL
    SELECT 41,N'SLK32 AMG' UNION ALL
    SELECT 41,N'SLK320' UNION ALL
    SELECT 41,N'SLK350' UNION ALL
    SELECT 41,N'SLK55 AMG' UNION ALL
    SELECT 41,N'V200' UNION ALL
    SELECT 41,N'V220' UNION ALL
    SELECT 41,N'V230' UNION ALL
    SELECT 41,N'V250' UNION ALL
    SELECT 41,N'V280' UNION ALL
    SELECT 2,N'A4 (B5)' UNION ALL
    SELECT 2,N'A4 (B6)' UNION ALL
    SELECT 47,N'Astra F' UNION ALL
    SELECT 47,N'Astra G' UNION ALL
    SELECT 47,N'Astra H' UNION ALL
    SELECT 47,N'Astra J' UNION ALL
    SELECT 47,N'Astra K' UNION ALL
    SELECT 62,N'Golf 2' UNION ALL
    SELECT 62,N'Golf II' UNION ALL
    SELECT 62,N'Golf 3' UNION ALL
    SELECT 62,N'Golf III' UNION ALL
    SELECT 62,N'Golf 4' UNION ALL
    SELECT 62,N'Golf IV' UNION ALL
    SELECT 62,N'Golf 5' UNION ALL
    SELECT 62,N'Golf V' UNION ALL
    SELECT 62,N'Golf 6' UNION ALL
    SELECT 62,N'Golf VI' UNION ALL
    SELECT 62,N'Golf 7' UNION ALL
    SELECT 62,N'Golf VII' UNION ALL
    SELECT 62,N'Passat B2' UNION ALL
    SELECT 62,N'Passat B3' UNION ALL
    SELECT 62,N'Passat B4' UNION ALL
    SELECT 62,N'Passat B5' UNION ALL
    SELECT 62,N'Passat B6' UNION ALL
    SELECT 62,N'Passat B7' UNION ALL
    SELECT 62,N'Passat B8' UNION ALL
    SELECT 61,N'Carina' UNION ALL
    SELECT 52,N'Scenic II' UNION ALL
    SELECT 41,N'E-klasse (W124)' UNION ALL
    SELECT 41,N'Atego' UNION ALL
    SELECT 41,N'Т1 207D - 410D' UNION ALL
    SELECT 2,N'A6 Avant (C5)'
END