CREATE UNIQUE NONCLUSTERED INDEX [ixCarModel_CarBrandId_Name] ON [dbo].[CarModel]
(
    [CarBrandId] ASC,
    [Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
