CREATE UNIQUE NONCLUSTERED INDEX [ixSite_SiteURL_CountryId] ON [dbo].[Site]
(
    [SiteUrl] ASC,
    [CountryId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
