 CREATE TABLE CarParsing(
    CarParsingId        INT NOT NULL IDENTITY(1,1),
    CarBrand            NVARCHAR(1000) NULL,
    Model               NVARCHAR(1000) NULL,
    SiteUrl             NVARCHAR(2000) NULL,
    Price               NVARCHAR(1000) NULL,
    BodyType            NVARCHAR(1000) NULL,
    ModelYear           NVARCHAR(1000) NULL,
    EngineType          NVARCHAR(200) NULL,
    EngineSize          NVARCHAR(1000) NULL,
    TransmissionType    NVARCHAR(1000) NULL,
    DriveType           NVARCHAR(1000) NULL,
    Condition           NVARCHAR(10) NULL,
    Mileage             NVARCHAR(1000) NULL,
    Color               NVARCHAR(100) NULL,
    SellerType          NVARCHAR(100) NULL,
    IsSwap              NVARCHAR(100) NULL,
    [Description]       NVARCHAR(2000) NULL,
    PageCreatedOn       NVARCHAR(100) NULL,
    CreatedOn           DATETIME NOT NULL,
    IsPageExist         BIT
    )