 CREATE TABLE CarParsing(
	ID					INT NOT NULL IDENTITY(1, 1),
	CarBrand			NVARCHAR(1000),
	Model				NVARCHAR(1000),
	SiteUrl				NVARCHAR(2000),
	Price				NVARCHAR(20),
	BodyType			NVARCHAR(1000),
	ModelYear			NVARCHAR(10),
	EngineType			NVARCHAR(200),
	EngineSize			NVARCHAR(10),
	TransmissionType	NVARCHAR(100),
	DriveType			NVARCHAR(100),
	Condition			NVARCHAR(10),
	Mileage				NVARCHAR(50),
	Color				NVARCHAR(100),
	SellerType			NVARCHAR(100),
	IsCustomsCleared	NVARCHAR(100),
	IsSwap				NVARCHAR(100),
	[Description]		NVARCHAR(2000),
	CreatedOn			NVARCHAR(100),
	UploadDate			DATETIME NOT NULL,
	IsPageExist			BIT
	)